/**
 * Cambridge English Pre-A1 Starters Wordlist (~470 단어, 토픽별).
 * 출처: vocabulary-master.html 의 자체 큐레이션. 학습 단원 시드용.
 */
export interface CambridgeTopic {
  id: string;
  emoji: string;
  nameKo: string;
  nameEn: string;
  words: string[];
}

export const CAMBRIDGE_STARTERS_TOPICS: CambridgeTopic[] = [
  {
    id: 'animals',
    emoji: '🦁',
    nameKo: '동물',
    nameEn: 'Animals',
    words: [
      'bird',
      'cat',
      'chicken',
      'cow',
      'crocodile',
      'dog',
      'donkey',
      'duck',
      'elephant',
      'fish',
      'frog',
      'giraffe',
      'goat',
      'horse',
      'kangaroo',
      'lion',
      'monkey',
      'mouse',
      'panda',
      'sheep',
      'snake',
      'spider',
      'tiger',
    ],
  },
  {
    id: 'body',
    emoji: '👁',
    nameKo: '몸과 얼굴',
    nameEn: 'Body & Face',
    words: [
      'arm',
      'body',
      'ear',
      'eye',
      'face',
      'foot',
      'hair',
      'hand',
      'head',
      'leg',
      'mouth',
      'nose',
      'person',
      'smile',
      'tooth',
    ],
  },
  {
    id: 'clothes',
    emoji: '👕',
    nameKo: '옷',
    nameEn: 'Clothes',
    words: [
      'bag',
      'dress',
      'glasses',
      'handbag',
      'hat',
      'jacket',
      'jeans',
      'shirt',
      'shoe',
      'skirt',
      'sock',
      't-shirt',
      'trousers',
      'watch',
    ],
  },
  {
    id: 'colours',
    emoji: '🎨',
    nameKo: '색깔',
    nameEn: 'Colours',
    words: [
      'black',
      'blue',
      'brown',
      'green',
      'grey',
      'orange',
      'pink',
      'purple',
      'red',
      'white',
      'yellow',
    ],
  },
  {
    id: 'family',
    emoji: '👨‍👩‍👧',
    nameKo: '가족과 친구',
    nameEn: 'Family & Friends',
    words: [
      'baby',
      'boy',
      'brother',
      'dad',
      'daughter',
      'family',
      'father',
      'friend',
      'girl',
      'grandfather',
      'grandmother',
      'mother',
      'mum',
      'parents',
      'sister',
      'son',
    ],
  },
  {
    id: 'food',
    emoji: '🍎',
    nameKo: '음식과 음료',
    nameEn: 'Food & Drink',
    words: [
      'apple',
      'banana',
      'bean',
      'bread',
      'breakfast',
      'burger',
      'cake',
      'candy',
      'carrot',
      'chips',
      'chocolate',
      'coconut',
      'dinner',
      'drink',
      'egg',
      'food',
      'fruit',
      'grape',
      'ice cream',
      'juice',
      'lemon',
      'lime',
      'lunch',
      'mango',
      'meat',
      'milk',
      'onion',
      'orange',
      'pea',
      'pear',
      'pineapple',
      'potato',
      'rice',
      'sausage',
      'tomato',
      'vegetable',
      'water',
      'watermelon',
    ],
  },
  {
    id: 'health',
    emoji: '🏥',
    nameKo: '건강',
    nameEn: 'Health',
    words: ['doctor', 'hospital', 'ill', 'sick', 'well'],
  },
  {
    id: 'home',
    emoji: '🏠',
    nameKo: '집',
    nameEn: 'Home',
    words: [
      'armchair',
      'bath',
      'bathroom',
      'bed',
      'bedroom',
      'bookcase',
      'bookshelf',
      'camera',
      'clock',
      'computer',
      'cupboard',
      'dining room',
      'door',
      'fan',
      'flat',
      'floor',
      'garden',
      'hall',
      'home',
      'house',
      'kitchen',
      'lamp',
      'living room',
      'lunch box',
      'mat',
      'mirror',
      'phone',
      'picture',
      'radio',
      'room',
      'rug',
      'shelf',
      'shower',
      'sofa',
      'table',
      'telephone',
      'television',
      'toy',
      'tv',
      'wall',
      'window',
      'yard',
    ],
  },
  {
    id: 'numbers',
    emoji: '🔢',
    nameKo: '숫자',
    nameEn: 'Numbers',
    words: [
      'zero',
      'one',
      'two',
      'three',
      'four',
      'five',
      'six',
      'seven',
      'eight',
      'nine',
      'ten',
      'eleven',
      'twelve',
      'thirteen',
      'fourteen',
      'fifteen',
      'sixteen',
      'seventeen',
      'eighteen',
      'nineteen',
      'twenty',
    ],
  },
  {
    id: 'places',
    emoji: '🌍',
    nameKo: '장소와 방향',
    nameEn: 'Places & Directions',
    words: ['address', 'beach', 'park', 'road', 'shop', 'street', 'town'],
  },
  {
    id: 'school',
    emoji: '🏫',
    nameKo: '학교',
    nameEn: 'School',
    words: [
      'alphabet',
      'answer',
      'book',
      'class',
      'classmate',
      'classroom',
      'desk',
      'english',
      'eraser',
      'lesson',
      'letter',
      'name',
      'page',
      'pen',
      'pencil',
      'question',
      'ruler',
      'school',
      'schoolbag',
      'student',
      'teacher',
      'word',
    ],
  },
  {
    id: 'sports',
    emoji: '⚽',
    nameKo: '스포츠와 여가',
    nameEn: 'Sports & Leisure',
    words: [
      'ball',
      'balloon',
      'bike',
      'board game',
      'boat',
      'dance',
      'doll',
      'drawing',
      'game',
      'hobby',
      'kite',
      'music',
      'paint',
      'photo',
      'play',
      'robot',
      'sing',
      'swim',
      'table tennis',
      'tennis',
      'toy',
      'train',
      'walk',
    ],
  },
  {
    id: 'world',
    emoji: '🌳',
    nameKo: '우리 주변 세상',
    nameEn: 'World Around Us',
    words: [
      'bus',
      'car',
      'cloud',
      'country',
      'day',
      'evening',
      'field',
      'flower',
      'jungle',
      'lake',
      'morning',
      'mountain',
      'night',
      'ocean',
      'plant',
      'rainbow',
      'river',
      'sea',
      'season',
      'sky',
      'snow',
      'star',
      'stone',
      'sun',
      'tree',
      'water',
      'weather',
      'wind',
      'world',
    ],
  },
  {
    id: 'verbs',
    emoji: '🏃',
    nameKo: '동사',
    nameEn: 'Verbs',
    words: [
      'be',
      'buy',
      'can',
      'catch',
      'choose',
      'clap',
      'clean',
      'close',
      'come',
      'count',
      'cry',
      'do',
      'draw',
      'drink',
      'drive',
      'eat',
      'find',
      'fly',
      'get',
      'give',
      'go',
      'have',
      'hear',
      'help',
      'hit',
      'hold',
      'jump',
      'kick',
      'know',
      'laugh',
      'like',
      'listen',
      'live',
      'look',
      'love',
      'make',
      'meet',
      'need',
      'open',
      'paint',
      'play',
      'point',
      'put',
      'read',
      'ride',
      'run',
      'say',
      'see',
      'sing',
      'sit',
      'sleep',
      'smile',
      'speak',
      'stand',
      'swim',
      'take',
      'talk',
      'think',
      'throw',
      'walk',
      'want',
      'watch',
      'wear',
      'write',
    ],
  },
  {
    id: 'adj',
    emoji: '✨',
    nameKo: '형용사',
    nameEn: 'Adjectives',
    words: [
      'angry',
      'beautiful',
      'big',
      'bored',
      'clean',
      'cold',
      'dirty',
      'every',
      'excited',
      'fast',
      'fat',
      'favourite',
      'friendly',
      'frightened',
      'funny',
      'good',
      'great',
      'happy',
      'hot',
      'hungry',
      'last',
      'long',
      'naughty',
      'new',
      'nice',
      'old',
      'poor',
      'rich',
      'sad',
      'scared',
      'short',
      'slow',
      'small',
      'sunny',
      'surprised',
      'tall',
      'tasty',
      'thirsty',
      'tired',
      'ugly',
      'wet',
      'wonderful',
      'young',
    ],
  },
  {
    id: 'adv',
    emoji: '📍',
    nameKo: '부사',
    nameEn: 'Adverbs',
    words: ['here', 'now', 'please', 'today', 'tomorrow', 'very', 'well', 'yesterday'],
  },
];

export const CAMBRIDGE_TOTAL_WORDS = CAMBRIDGE_STARTERS_TOPICS.reduce(
  (a, t) => a + t.words.length,
  0
);
