export const TARGET_AGES = ['4-5', '5-7', '7-8'] as const;
export type TargetAge = (typeof TARGET_AGES)[number];

export const ART_STYLES = [
  { id: 'modern-illustration', label: '현대 일러스트', prompt: 'Modern Illustration' },
  { id: 'watercolor', label: '수채화', prompt: 'Watercolor' },
  { id: 'cartoon', label: '카툰', prompt: 'Cartoon' },
  { id: 'traditional', label: '전통 동화책', prompt: 'Traditional Storybook' },
  { id: 'animation', label: '애니메이션', prompt: 'Animation' },
  { id: 'oil-painting', label: '유화', prompt: 'Oil Painting' },
  { id: 'pencil-sketch', label: '연필 스케치', prompt: 'Pencil Sketch' },
] as const;

export const ASPECT_RATIOS = ['16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '1:1'] as const;
export type AspectRatio = (typeof ASPECT_RATIOS)[number];

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: '영어' },
  { code: 'ja', label: '일본어' },
  { code: 'zh', label: '중국어' },
  { code: 'es', label: '스페인어' },
  { code: 'fr', label: '프랑스어' },
  { code: 'de', label: '독일어' },
] as const;

export const TTS_PROVIDERS = ['gemini', 'minimax', 'elevenlabs'] as const;
export type TtsProvider = (typeof TTS_PROVIDERS)[number];

export const TTS_VOICES = [
  { id: 'Leda', label: '레다', description: 'Youthful' },
  { id: 'Sulafat', label: '술라파트', description: 'Warm' },
  { id: 'Vindemiatrix', label: '빈데미아트릭스', description: 'Gentle' },
  { id: 'Achird', label: '아키르드', description: 'Friendly' },
  { id: 'Sadachbia', label: '사다크비아', description: 'Lively' },
  { id: 'Puck', label: '퍽', description: 'Upbeat' },
  { id: 'Kore', label: '코레', description: 'Firm' },
  { id: 'Achernar', label: '아케르나르', description: 'Soft' },
  { id: 'Zephyr', label: '제피르', description: 'Bright' },
  { id: 'Aoede', label: '아오에데', description: 'Breezy' },
] as const;

export const IMAGE_MODELS = [
  {
    id: 'gemini-2.5-flash-image',
    label: 'Nano Banana',
    description: '빠르고 효율적, 대량 생성에 적합',
  },
  {
    id: 'gemini-3.1-flash-image-preview',
    label: 'Nano Banana 2',
    description: '고효율, 빠른 속도 + 고품질',
  },
  {
    id: 'gemini-3-pro-image-preview',
    label: 'Nano Banana Pro',
    description: '최고 품질, 복잡한 지시 이해력 우수',
  },
  {
    id: 'imagen-4.0-fast-generate-001',
    label: 'Imagen 4 Fast',
    description: '텍스트→이미지 특화, 초고속 생성',
  },
  {
    id: 'imagen-4.0-generate-001',
    label: 'Imagen 4',
    description: '텍스트→이미지 특화, 고품질 2K',
  },
  {
    id: 'imagen-4.0-ultra-generate-001',
    label: 'Imagen 4 Ultra',
    description: '최고 품질 2K, 텍스트 렌더링 우수',
  },
] as const;
export type ImageModelId = (typeof IMAGE_MODELS)[number]['id'];

export const DEFAULT_IMAGE_MODEL = 'gemini-3.1-flash-image-preview' satisfies ImageModelId;

export const TEXT_MODELS = [
  { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', description: '빠르고 효율적' },
  { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro', description: '고품질, 정교한 추론' },
  { id: 'gemini-3-flash-preview', label: 'Gemini 3 Flash', description: '차세대 빠른 모델' },
  { id: 'gemini-3-pro-preview', label: 'Gemini 3 Pro', description: '차세대 고급 추론' },
  {
    id: 'gemini-3.1-pro-preview',
    label: 'Gemini 3.1 Pro',
    description: '최신, 100만 토큰 컨텍스트',
  },
] as const;
export type TextModelId = (typeof TEXT_MODELS)[number]['id'];
export const DEFAULT_TEXT_MODEL = 'gemini-2.5-flash' satisfies TextModelId;

export const MAX_IMAGE_HISTORY = 10;
export const MAX_FILE_SIZE_MB = 5;

// === Phonics 상수 ===

export const PHONICS_LANGUAGES = [
  { id: 'english' as const, label: '영어 파닉스' },
  { id: 'korean' as const, label: '한글 파닉스' },
] as const;

export const ENGLISH_PHONICS_CURRICULUM = [
  // === 1권: Single Letter Sounds — 알파벳 개별 음가 ===
  {
    level: 'book1',
    name: 'Book 1: Single Letter Sounds',
    description: '알파벳 Aa~Zz 개별 음가 (initial sounds)',
    units: [
      {
        id: 'en-b1-u1',
        title: 'Unit 1: Aa Bb Cc',
        phonemes: ['a', 'b', 'c'],
        patterns: ['initial sounds'],
        sampleWords: ['alligator', 'ant', 'apple', 'bag', 'bat', 'book', 'cap', 'cat', 'cup'],
      },
      {
        id: 'en-b1-u2',
        title: 'Unit 2: Dd Ee Ff',
        phonemes: ['d', 'e', 'f'],
        patterns: ['initial sounds'],
        sampleWords: ['desk', 'dog', 'duck', 'egg', 'elbow', 'elephant', 'fan', 'fish', 'fork'],
      },
      {
        id: 'en-b1-u3',
        title: 'Unit 3: Gg Hh Ii',
        phonemes: ['g', 'h', 'i'],
        patterns: ['initial sounds'],
        sampleWords: ['game', 'gift', 'gorilla', 'hand', 'hat', 'hippo', 'igloo', 'iguana', 'ink'],
      },
      {
        id: 'en-b1-u4',
        title: 'Unit 4: Jj Kk Ll',
        phonemes: ['j', 'k', 'l'],
        patterns: ['initial sounds'],
        sampleWords: ['jacket', 'jam', 'jet', 'key', 'king', 'kiwi', 'lamp', 'lemon', 'lion'],
      },
      {
        id: 'en-b1-u5',
        title: 'Unit 5: Mm Nn Oo',
        phonemes: ['m', 'n', 'o'],
        patterns: ['initial sounds'],
        sampleWords: ['map', 'melon', 'mouse', 'nest', 'net', 'nut', 'octopus', 'ostrich', 'ox'],
      },
      {
        id: 'en-b1-u6',
        title: 'Unit 6: Pp Qq Rr',
        phonemes: ['p', 'q', 'r'],
        patterns: ['initial sounds'],
        sampleWords: [
          'panda',
          'pen',
          'piano',
          'queen',
          'question',
          'quiet',
          'rabbit',
          'ring',
          'robot',
        ],
      },
      {
        id: 'en-b1-u7',
        title: 'Unit 7: Ss Tt Uu Vv',
        phonemes: ['s', 't', 'u', 'v'],
        patterns: ['initial sounds'],
        sampleWords: [
          'sand',
          'sock',
          'sun',
          'ten',
          'tiger',
          'top',
          'umbrella',
          'under',
          'up',
          'vase',
          'vest',
          'violin',
        ],
      },
      {
        id: 'en-b1-u8',
        title: 'Unit 8: Ww Xx Yy Zz',
        phonemes: ['w', 'x', 'y', 'z'],
        patterns: ['initial sounds'],
        sampleWords: [
          'watch',
          'watermelon',
          'window',
          'box',
          'fox',
          'six',
          'yacht',
          'yellow',
          'yo-yo',
          'zebra',
          'zero',
          'zoo',
        ],
      },
    ],
  },
  // === 2권: Short Vowels — 단모음 CVC ===
  {
    level: 'book2',
    name: 'Book 2: Short Vowels',
    description: '단모음 CVC 단어 (word families)',
    units: [
      {
        id: 'en-b2-u1',
        title: 'Unit 1: Short Vowel a (1)',
        phonemes: ['short-a'],
        patterns: ['_an', '_at'],
        sampleWords: ['can', 'fan', 'man', 'pan', 'bat', 'cat', 'hat', 'mat'],
      },
      {
        id: 'en-b2-u2',
        title: 'Unit 2: Short Vowel a (2)',
        phonemes: ['short-a'],
        patterns: ['_ap', '_ad', '_am'],
        sampleWords: ['cap', 'lap', 'map', 'tap', 'dad', 'sad', 'dam', 'jam'],
      },
      {
        id: 'en-b2-u3',
        title: 'Unit 3: Short Vowel i (1)',
        phonemes: ['short-i'],
        patterns: ['_ip', '_it', '_ix'],
        sampleWords: ['dip', 'hip', 'lip', 'rip', 'hit', 'sit', 'mix', 'six'],
      },
      {
        id: 'en-b2-u4',
        title: 'Unit 4: Short Vowel i (2)',
        phonemes: ['short-i'],
        patterns: ['_ib', '_id', '_ig', '_in'],
        sampleWords: ['bib', 'rib', 'kid', 'lid', 'dig', 'wig', 'fin', 'pin'],
      },
      {
        id: 'en-b2-u5',
        title: 'Unit 5: Short Vowel e',
        phonemes: ['short-e'],
        patterns: ['_et', '_ed', '_en'],
        sampleWords: ['jet', 'net', 'vet', 'wet', 'bed', 'red', 'hen', 'pen'],
      },
      {
        id: 'en-b2-u6',
        title: 'Unit 6: Short Vowel o',
        phonemes: ['short-o'],
        patterns: ['_og', '_op', '_ot', '_ox'],
        sampleWords: ['dog', 'log', 'hop', 'mop', 'hot', 'pot', 'box', 'fox'],
      },
      {
        id: 'en-b2-u7',
        title: 'Unit 7: Short Vowel u (1)',
        phonemes: ['short-u'],
        patterns: ['_ug', '_ub', '_up'],
        sampleWords: ['bug', 'hug', 'mug', 'rug', 'rub', 'tub', 'cup', 'pup'],
      },
      {
        id: 'en-b2-u8',
        title: 'Unit 8: Short Vowel u (2)',
        phonemes: ['short-u'],
        patterns: ['_un', '_ud', '_ut'],
        sampleWords: ['bun', 'fun', 'run', 'sun', 'bud', 'mud', 'cut', 'nut'],
      },
    ],
  },
  // === 3권: Long Vowels — 장모음 Magic e ===
  {
    level: 'book3',
    name: 'Book 3: Long Vowels (Magic e)',
    description: 'Magic e 장모음 CVCe 단어',
    units: [
      {
        id: 'en-b3-u1',
        title: 'Unit 1: Long Vowel a (1)',
        phonemes: ['long-a'],
        patterns: ['_ake', '_ape', '_ave'],
        sampleWords: ['bake', 'cake', 'lake', 'rake', 'cape', 'tape', 'cave', 'wave'],
      },
      {
        id: 'en-b3-u2',
        title: 'Unit 2: Long Vowel a (2)',
        phonemes: ['long-a'],
        patterns: ['_ame', '_ane', '_ase', '_ate'],
        sampleWords: ['game', 'name', 'came', 'lane', 'case', 'vase', 'date', 'gate'],
      },
      {
        id: 'en-b3-u3',
        title: 'Unit 3: Long Vowel i (1)',
        phonemes: ['long-i'],
        patterns: ['_ine', '_ike', '_ime'],
        sampleWords: ['line', 'nine', 'pine', 'vine', 'bike', 'hike', 'lime', 'time'],
      },
      {
        id: 'en-b3-u4',
        title: 'Unit 4: Long Vowel i (2)',
        phonemes: ['long-i'],
        patterns: ['_ide', '_ipe', '_ite', '_ive'],
        sampleWords: ['hide', 'ride', 'pipe', 'wipe', 'bite', 'kite', 'dive', 'five'],
      },
      {
        id: 'en-b3-u5',
        title: 'Unit 5: Long Vowel o (1)',
        phonemes: ['long-o'],
        patterns: ['_ose', '_ope', '_ote'],
        sampleWords: ['hose', 'nose', 'pose', 'rose', 'hope', 'rope', 'note', 'vote'],
      },
      {
        id: 'en-b3-u6',
        title: 'Unit 6: Long Vowel o (2)',
        phonemes: ['long-o'],
        patterns: ['_ole', '_ome', '_one'],
        sampleWords: ['hole', 'mole', 'pole', 'sole', 'dome', 'home', 'bone', 'cone'],
      },
      {
        id: 'en-b3-u7',
        title: 'Unit 7: Long Vowel u',
        phonemes: ['long-u'],
        patterns: ['_ube', '_ute', '_une', '_ule'],
        sampleWords: ['cube', 'tube', 'cute', 'mute', 'dune', 'June', 'tune', 'mule'],
      },
    ],
  },
  // === 4권: Consonant Blends & Digraphs ===
  {
    level: 'book4',
    name: 'Book 4: Consonant Blends & Digraphs',
    description: '자음군(bl, cr, st...) + 이중자음(ch, sh, th, ph, wh)',
    units: [
      {
        id: 'en-b4-u1',
        title: 'Unit 1: bl cl fl',
        phonemes: ['bl', 'cl', 'fl'],
        patterns: ['bl_', 'cl_', 'fl_'],
        sampleWords: [
          'black',
          'blade',
          'block',
          'blue',
          'clam',
          'clap',
          'cliff',
          'clock',
          'flag',
          'flame',
          'flap',
          'flute',
        ],
      },
      {
        id: 'en-b4-u2',
        title: 'Unit 2: br cr fr',
        phonemes: ['br', 'cr', 'fr'],
        patterns: ['br_', 'cr_', 'fr_'],
        sampleWords: [
          'brake',
          'brave',
          'brick',
          'bride',
          'crab',
          'crack',
          'crane',
          'crib',
          'frame',
          'frog',
          'front',
          'frost',
        ],
      },
      {
        id: 'en-b4-u3',
        title: 'Unit 3: gl pl sl',
        phonemes: ['gl', 'pl', 'sl'],
        patterns: ['gl_', 'pl_', 'sl_'],
        sampleWords: [
          'glass',
          'globe',
          'glove',
          'glue',
          'plane',
          'plant',
          'plate',
          'plum',
          'sled',
          'slice',
          'slide',
          'slim',
        ],
      },
      {
        id: 'en-b4-u4',
        title: 'Unit 4: dr pr tr',
        phonemes: ['dr', 'pr', 'tr'],
        patterns: ['dr_', 'pr_', 'tr_'],
        sampleWords: [
          'dragon',
          'dress',
          'drive',
          'drum',
          'press',
          'price',
          'print',
          'prize',
          'trace',
          'track',
          'truck',
          'tree',
        ],
      },
      {
        id: 'en-b4-u5',
        title: 'Unit 5: sm sn st sw',
        phonemes: ['sm', 'sn', 'st', 'sw'],
        patterns: ['sm_', 'sn_', 'st_', 'sw_'],
        sampleWords: [
          'smell',
          'smile',
          'smoke',
          'snack',
          'snake',
          'snore',
          'stone',
          'stop',
          'stove',
          'swan',
          'sweet',
          'swim',
        ],
      },
      {
        id: 'en-b4-u6',
        title: 'Unit 6: ng nk',
        phonemes: ['ng', 'nk'],
        patterns: ['_ng', '_nk'],
        sampleWords: [
          'bang',
          'fang',
          'king',
          'ring',
          'long',
          'song',
          'bank',
          'rank',
          'pink',
          'wink',
          'dunk',
          'junk',
        ],
      },
      {
        id: 'en-b4-u7',
        title: 'Unit 7: ch sh',
        phonemes: ['ch', 'sh'],
        patterns: ['ch_', '_ch', 'sh_', '_sh'],
        sampleWords: [
          'cherry',
          'chin',
          'bench',
          'branch',
          'catch',
          'shape',
          'ship',
          'shop',
          'brush',
          'fish',
          'wash',
        ],
      },
      {
        id: 'en-b4-u8',
        title: 'Unit 8: ph th wh',
        phonemes: ['ph', 'th', 'wh'],
        patterns: ['ph_', 'th_', 'wh_'],
        sampleWords: [
          'phone',
          'photo',
          'dolphin',
          'elephant',
          'thick',
          'thin',
          'bath',
          'teeth',
          'whale',
          'wheel',
          'whisper',
          'white',
        ],
      },
    ],
  },
  // === 5권: Double Letter Vowels & R-Controlled Vowels ===
  {
    level: 'book5',
    name: 'Book 5: Double Letter Vowels & R-Controlled',
    description: '이중모음(ee, ea, ai, ay, oi, oy, ow, ou) + R-통제 모음(ar, or, ir, er, ur)',
    units: [
      {
        id: 'en-b5-u1',
        title: 'Unit 1: ee ea (/iː/)',
        phonemes: ['ee', 'ea'],
        patterns: ['ee', 'ea'],
        sampleWords: [
          'bee',
          'feet',
          'green',
          'peel',
          'seed',
          'tree',
          'leaf',
          'meat',
          'peanut',
          'sea',
          'seal',
          'tea',
        ],
      },
      {
        id: 'en-b5-u2',
        title: 'Unit 2: oa ow (/oʊ/)',
        phonemes: ['oa', 'ow'],
        patterns: ['oa', 'ow'],
        sampleWords: [
          'boat',
          'coat',
          'goat',
          'road',
          'soap',
          'toast',
          'blow',
          'bowl',
          'pillow',
          'snow',
          'window',
        ],
      },
      {
        id: 'en-b5-u3',
        title: 'Unit 3: ai ay (/eɪ/)',
        phonemes: ['ai', 'ay'],
        patterns: ['ai', 'ay'],
        sampleWords: [
          'mail',
          'nail',
          'rail',
          'rain',
          'tail',
          'train',
          'clay',
          'gray',
          'hay',
          'play',
          'pray',
          'tray',
        ],
      },
      {
        id: 'en-b5-u4',
        title: 'Unit 4: oi oy (/ɔɪ/)',
        phonemes: ['oi', 'oy'],
        patterns: ['oi', 'oy'],
        sampleWords: [
          'boil',
          'coil',
          'coin',
          'foil',
          'oil',
          'point',
          'soil',
          'toilet',
          'boy',
          'joy',
          'soybean',
          'toy',
        ],
      },
      {
        id: 'en-b5-u5',
        title: 'Unit 5: ow ou (/aʊ/)',
        phonemes: ['ow', 'ou'],
        patterns: ['ow', 'ou'],
        sampleWords: [
          'brown',
          'clown',
          'cow',
          'crown',
          'gown',
          'owl',
          'blouse',
          'cloud',
          'count',
          'house',
          'mouse',
          'mouth',
        ],
      },
      {
        id: 'en-b5-u6',
        title: 'Unit 6: ir er ur (/ɜːr/)',
        phonemes: ['ir', 'er', 'ur'],
        patterns: ['ir', 'er', 'ur'],
        sampleWords: [
          'bird',
          'girl',
          'shirt',
          'skirt',
          'letter',
          'singer',
          'soccer',
          'teacher',
          'nurse',
          'purple',
          'purse',
          'turtle',
        ],
      },
      {
        id: 'en-b5-u7',
        title: 'Unit 7: ar or',
        phonemes: ['ar', 'or'],
        patterns: ['ar', 'or'],
        sampleWords: [
          'arm',
          'car',
          'card',
          'farmer',
          'park',
          'star',
          'cork',
          'corn',
          'fork',
          'horse',
          'north',
          'store',
        ],
      },
      {
        id: 'en-b5-u8',
        title: 'Unit 8: oo (/ʊ/ & /uː/)',
        phonemes: ['oo'],
        patterns: ['oo'],
        sampleWords: [
          'book',
          'cook',
          'foot',
          'hook',
          'look',
          'wood',
          'food',
          'goose',
          'moon',
          'pool',
          'spoon',
          'zoo',
        ],
      },
    ],
  },
] as const;

export const KOREAN_PHONICS_CURRICULUM = [
  {
    level: 'hangul1',
    name: '한글1: 기본음절',
    description: '모음과 자음(ㄱ~ㅎ) 기본 음절 학습',
    units: [
      {
        id: 'kr-h1-u1',
        title: 'unit 1: 모음 배우기',
        phonemes: ['ㅏ', 'ㅑ', 'ㅓ', 'ㅕ', 'ㅗ', 'ㅛ', 'ㅜ', 'ㅠ', 'ㅡ', 'ㅣ'],
        patterns: ['모음'],
        sampleWords: [],
        blending: [],
      },
      {
        id: 'kr-h1-u2',
        title: 'unit 2: ㄱ 배우기',
        phonemes: ['ㄱ'],
        patterns: ['자음+모음'],
        sampleWords: ['고기', '가구', '아기', '야구'],
        blending: [
          ['ㄱ', 'ㅏ', '가'],
          ['ㄱ', 'ㅑ', '갸'],
          ['ㄱ', 'ㅓ', '거'],
          ['ㄱ', 'ㅕ', '겨'],
          ['ㄱ', 'ㅗ', '고'],
          ['ㄱ', 'ㅛ', '교'],
          ['ㄱ', 'ㅜ', '구'],
          ['ㄱ', 'ㅠ', '규'],
          ['ㄱ', 'ㅡ', '그'],
          ['ㄱ', 'ㅣ', '기'],
        ],
      },
      {
        id: 'kr-h1-u3',
        title: 'unit 3: ㄴ 배우기',
        phonemes: ['ㄴ'],
        patterns: ['자음+모음'],
        sampleWords: ['나', '너', '누나', '누구야'],
        blending: [
          ['ㄴ', 'ㅏ', '나'],
          ['ㄴ', 'ㅑ', '냐'],
          ['ㄴ', 'ㅓ', '너'],
          ['ㄴ', 'ㅕ', '녀'],
          ['ㄴ', 'ㅗ', '노'],
          ['ㄴ', 'ㅛ', '뇨'],
          ['ㄴ', 'ㅜ', '누'],
          ['ㄴ', 'ㅠ', '뉴'],
          ['ㄴ', 'ㅡ', '느'],
          ['ㄴ', 'ㅣ', '니'],
        ],
      },
      {
        id: 'kr-h1-u4',
        title: 'unit 4: ㄷ 배우기',
        phonemes: ['ㄷ'],
        patterns: ['자음+모음'],
        sampleWords: ['두유', '도마', '기도', '구두'],
        blending: [
          ['ㄷ', 'ㅏ', '다'],
          ['ㄷ', 'ㅑ', '댜'],
          ['ㄷ', 'ㅓ', '더'],
          ['ㄷ', 'ㅕ', '뎌'],
          ['ㄷ', 'ㅗ', '도'],
          ['ㄷ', 'ㅛ', '됴'],
          ['ㄷ', 'ㅜ', '두'],
          ['ㄷ', 'ㅠ', '듀'],
          ['ㄷ', 'ㅡ', '드'],
          ['ㄷ', 'ㅣ', '디'],
        ],
      },
      {
        id: 'kr-h1-u5',
        title: 'unit 5: ㄹ 배우기',
        phonemes: ['ㄹ'],
        patterns: ['자음+모음'],
        sampleWords: ['오리', '너구리', '다리', '노루'],
        blending: [
          ['ㄹ', 'ㅏ', '라'],
          ['ㄹ', 'ㅑ', '랴'],
          ['ㄹ', 'ㅓ', '러'],
          ['ㄹ', 'ㅕ', '려'],
          ['ㄹ', 'ㅗ', '로'],
          ['ㄹ', 'ㅛ', '료'],
          ['ㄹ', 'ㅜ', '루'],
          ['ㄹ', 'ㅠ', '류'],
          ['ㄹ', 'ㅡ', '르'],
          ['ㄹ', 'ㅣ', '리'],
        ],
      },
      {
        id: 'kr-h1-u6',
        title: 'unit 6: ㅁ 배우기',
        phonemes: ['ㅁ'],
        patterns: ['자음+모음'],
        sampleWords: ['머리', '모두', '모기', '거미'],
        blending: [
          ['ㅁ', 'ㅏ', '마'],
          ['ㅁ', 'ㅑ', '먀'],
          ['ㅁ', 'ㅓ', '머'],
          ['ㅁ', 'ㅕ', '며'],
          ['ㅁ', 'ㅗ', '모'],
          ['ㅁ', 'ㅛ', '묘'],
          ['ㅁ', 'ㅜ', '무'],
          ['ㅁ', 'ㅠ', '뮤'],
          ['ㅁ', 'ㅡ', '므'],
          ['ㅁ', 'ㅣ', '미'],
        ],
      },
      {
        id: 'kr-h1-u7',
        title: 'unit 7: ㅂ 배우기',
        phonemes: ['ㅂ'],
        patterns: ['자음+모음'],
        sampleWords: ['바다', '비누', '나비', '두부'],
        blending: [
          ['ㅂ', 'ㅏ', '바'],
          ['ㅂ', 'ㅑ', '뱌'],
          ['ㅂ', 'ㅓ', '버'],
          ['ㅂ', 'ㅕ', '벼'],
          ['ㅂ', 'ㅗ', '보'],
          ['ㅂ', 'ㅛ', '뵤'],
          ['ㅂ', 'ㅜ', '부'],
          ['ㅂ', 'ㅠ', '뷰'],
          ['ㅂ', 'ㅡ', '브'],
          ['ㅂ', 'ㅣ', '비'],
        ],
      },
      {
        id: 'kr-h1-u8',
        title: 'unit 8: ㅅ 배우기',
        phonemes: ['ㅅ'],
        patterns: ['자음+모음'],
        sampleWords: ['사자', '버스', '가수', '미소'],
        blending: [
          ['ㅅ', 'ㅏ', '사'],
          ['ㅅ', 'ㅑ', '샤'],
          ['ㅅ', 'ㅓ', '서'],
          ['ㅅ', 'ㅕ', '셔'],
          ['ㅅ', 'ㅗ', '소'],
          ['ㅅ', 'ㅛ', '쇼'],
          ['ㅅ', 'ㅜ', '수'],
          ['ㅅ', 'ㅠ', '슈'],
          ['ㅅ', 'ㅡ', '스'],
          ['ㅅ', 'ㅣ', '시'],
        ],
      },
      {
        id: 'kr-h1-u9',
        title: 'unit 9: ㅇ 배우기',
        phonemes: ['ㅇ'],
        patterns: ['자음+모음'],
        sampleWords: ['우주', '여우', '우유', '어부'],
        blending: [
          ['ㅇ', 'ㅏ', '아'],
          ['ㅇ', 'ㅑ', '야'],
          ['ㅇ', 'ㅓ', '어'],
          ['ㅇ', 'ㅕ', '여'],
          ['ㅇ', 'ㅗ', '오'],
          ['ㅇ', 'ㅛ', '요'],
          ['ㅇ', 'ㅜ', '우'],
          ['ㅇ', 'ㅠ', '유'],
          ['ㅇ', 'ㅡ', '으'],
          ['ㅇ', 'ㅣ', '이'],
        ],
      },
      {
        id: 'kr-h1-u10',
        title: 'unit 10: ㅈ 배우기',
        phonemes: ['ㅈ'],
        patterns: ['자음+모음'],
        sampleWords: ['지구', '지도', '자두', '모자'],
        blending: [
          ['ㅈ', 'ㅏ', '자'],
          ['ㅈ', 'ㅑ', '쟈'],
          ['ㅈ', 'ㅓ', '저'],
          ['ㅈ', 'ㅕ', '져'],
          ['ㅈ', 'ㅗ', '조'],
          ['ㅈ', 'ㅛ', '죠'],
          ['ㅈ', 'ㅜ', '주'],
          ['ㅈ', 'ㅠ', '쥬'],
          ['ㅈ', 'ㅡ', '즈'],
          ['ㅈ', 'ㅣ', '지'],
        ],
      },
      {
        id: 'kr-h1-u11',
        title: 'unit 11: ㅊ 배우기',
        phonemes: ['ㅊ'],
        patterns: ['자음+모음'],
        sampleWords: ['치마', '치즈', '마차', '기차'],
        blending: [
          ['ㅊ', 'ㅏ', '차'],
          ['ㅊ', 'ㅑ', '챠'],
          ['ㅊ', 'ㅓ', '처'],
          ['ㅊ', 'ㅕ', '쳐'],
          ['ㅊ', 'ㅗ', '초'],
          ['ㅊ', 'ㅛ', '쵸'],
          ['ㅊ', 'ㅜ', '추'],
          ['ㅊ', 'ㅠ', '츄'],
          ['ㅊ', 'ㅡ', '츠'],
          ['ㅊ', 'ㅣ', '치'],
        ],
      },
      {
        id: 'kr-h1-u12',
        title: 'unit 12: ㅋ 배우기',
        phonemes: ['ㅋ'],
        patterns: ['자음+모음'],
        sampleWords: ['쿠키', '코코아', '마이크', '카드'],
        blending: [
          ['ㅋ', 'ㅏ', '카'],
          ['ㅋ', 'ㅑ', '캬'],
          ['ㅋ', 'ㅓ', '커'],
          ['ㅋ', 'ㅕ', '켜'],
          ['ㅋ', 'ㅗ', '코'],
          ['ㅋ', 'ㅛ', '쿄'],
          ['ㅋ', 'ㅜ', '쿠'],
          ['ㅋ', 'ㅠ', '큐'],
          ['ㅋ', 'ㅡ', '크'],
          ['ㅋ', 'ㅣ', '키'],
        ],
      },
      {
        id: 'kr-h1-u13',
        title: 'unit 13: ㅌ 배우기',
        phonemes: ['ㅌ'],
        patterns: ['자음+모음'],
        sampleWords: ['타조', '하트', '기타', '치타'],
        blending: [
          ['ㅌ', 'ㅏ', '타'],
          ['ㅌ', 'ㅑ', '탸'],
          ['ㅌ', 'ㅓ', '터'],
          ['ㅌ', 'ㅕ', '텨'],
          ['ㅌ', 'ㅗ', '토'],
          ['ㅌ', 'ㅛ', '툐'],
          ['ㅌ', 'ㅜ', '투'],
          ['ㅌ', 'ㅠ', '튜'],
          ['ㅌ', 'ㅡ', '트'],
          ['ㅌ', 'ㅣ', '티'],
        ],
      },
      {
        id: 'kr-h1-u14',
        title: 'unit 14: ㅍ 배우기',
        phonemes: ['ㅍ'],
        patterns: ['자음+모음'],
        sampleWords: ['피자', '파리', '포도', '소파'],
        blending: [
          ['ㅍ', 'ㅏ', '파'],
          ['ㅍ', 'ㅑ', '퍄'],
          ['ㅍ', 'ㅓ', '퍼'],
          ['ㅍ', 'ㅕ', '펴'],
          ['ㅍ', 'ㅗ', '포'],
          ['ㅍ', 'ㅛ', '표'],
          ['ㅍ', 'ㅜ', '푸'],
          ['ㅍ', 'ㅠ', '퓨'],
          ['ㅍ', 'ㅡ', '프'],
          ['ㅍ', 'ㅣ', '피'],
        ],
      },
      {
        id: 'kr-h1-u15',
        title: 'unit 15: ㅎ 배우기',
        phonemes: ['ㅎ'],
        patterns: ['자음+모음'],
        sampleWords: ['하마', '호두', '휴지', '호수'],
        blending: [
          ['ㅎ', 'ㅏ', '하'],
          ['ㅎ', 'ㅑ', '햐'],
          ['ㅎ', 'ㅓ', '허'],
          ['ㅎ', 'ㅕ', '혀'],
          ['ㅎ', 'ㅗ', '호'],
          ['ㅎ', 'ㅛ', '효'],
          ['ㅎ', 'ㅜ', '후'],
          ['ㅎ', 'ㅠ', '휴'],
          ['ㅎ', 'ㅡ', '흐'],
          ['ㅎ', 'ㅣ', '히'],
        ],
      },
    ],
  },
  {
    level: 'hangul2',
    name: '한글2: 받침',
    description: 'ㅇ, ㄱ, ㄴ, ㄹ, ㅅ, ㅁ, ㅂ 받침 학습',
    units: [
      {
        id: 'kr-h2-u1',
        title: 'unit 1: ㅇ 받침 배우기',
        phonemes: ['받침ㅇ'],
        patterns: ['받침'],
        sampleWords: ['형', '풍당', '농구', '시장'],
        blending: [
          ['ㄱ', 'ㅏ', 'ㅇ', '강'],
          ['ㄴ', 'ㅏ', 'ㅇ', '낭'],
          ['ㄷ', 'ㅏ', 'ㅇ', '당'],
          ['ㄹ', 'ㅏ', 'ㅇ', '랑'],
          ['ㅁ', 'ㅏ', 'ㅇ', '망'],
          ['ㅂ', 'ㅏ', 'ㅇ', '방'],
          ['ㅅ', 'ㅏ', 'ㅇ', '상'],
          ['ㅇ', 'ㅏ', 'ㅇ', '앙'],
          ['ㅈ', 'ㅏ', 'ㅇ', '장'],
          ['ㅊ', 'ㅏ', 'ㅇ', '창'],
          ['ㅋ', 'ㅏ', 'ㅇ', '캉'],
          ['ㅌ', 'ㅏ', 'ㅇ', '탕'],
          ['ㅍ', 'ㅏ', 'ㅇ', '팡'],
          ['ㅎ', 'ㅏ', 'ㅇ', '항'],
        ],
      },
      {
        id: 'kr-h2-u2',
        title: 'unit 2: ㄱ 받침 배우기',
        phonemes: ['받침ㄱ'],
        patterns: ['받침'],
        sampleWords: ['학교', '축구', '악어', '탁구'],
        blending: [
          ['ㄱ', 'ㅏ', 'ㄱ', '각'],
          ['ㄴ', 'ㅏ', 'ㄱ', '낙'],
          ['ㄷ', 'ㅏ', 'ㄱ', '닥'],
          ['ㄹ', 'ㅏ', 'ㄱ', '락'],
          ['ㅁ', 'ㅏ', 'ㄱ', '막'],
          ['ㅂ', 'ㅏ', 'ㄱ', '박'],
          ['ㅅ', 'ㅏ', 'ㄱ', '삭'],
          ['ㅇ', 'ㅏ', 'ㄱ', '악'],
          ['ㅈ', 'ㅏ', 'ㄱ', '작'],
          ['ㅊ', 'ㅏ', 'ㄱ', '착'],
          ['ㅋ', 'ㅏ', 'ㄱ', '칵'],
          ['ㅌ', 'ㅏ', 'ㄱ', '탁'],
          ['ㅍ', 'ㅏ', 'ㄱ', '팍'],
          ['ㅎ', 'ㅏ', 'ㄱ', '학'],
        ],
      },
      {
        id: 'kr-h2-u3',
        title: 'unit 3: ㄴ 받침 배우기',
        phonemes: ['받침ㄴ'],
        patterns: ['받침'],
        sampleWords: ['손', '눈', '언니', '잔디'],
        blending: [
          ['ㄱ', 'ㅏ', 'ㄴ', '간'],
          ['ㄴ', 'ㅏ', 'ㄴ', '난'],
          ['ㄷ', 'ㅏ', 'ㄴ', '단'],
          ['ㄹ', 'ㅏ', 'ㄴ', '란'],
          ['ㅁ', 'ㅏ', 'ㄴ', '만'],
          ['ㅂ', 'ㅏ', 'ㄴ', '반'],
          ['ㅅ', 'ㅏ', 'ㄴ', '산'],
          ['ㅇ', 'ㅏ', 'ㄴ', '안'],
          ['ㅈ', 'ㅏ', 'ㄴ', '잔'],
          ['ㅊ', 'ㅏ', 'ㄴ', '찬'],
          ['ㅋ', 'ㅏ', 'ㄴ', '칸'],
          ['ㅌ', 'ㅏ', 'ㄴ', '탄'],
          ['ㅍ', 'ㅏ', 'ㄴ', '판'],
          ['ㅎ', 'ㅏ', 'ㄴ', '한'],
        ],
      },
      {
        id: 'kr-h2-u4',
        title: 'unit 4: ㄹ 받침 배우기',
        phonemes: ['받침ㄹ'],
        patterns: ['받침'],
        sampleWords: ['별', '달', '하늘', '가을'],
        blending: [
          ['ㄱ', 'ㅏ', 'ㄹ', '갈'],
          ['ㄴ', 'ㅏ', 'ㄹ', '날'],
          ['ㄷ', 'ㅏ', 'ㄹ', '달'],
          ['ㄹ', 'ㅏ', 'ㄹ', '랄'],
          ['ㅁ', 'ㅏ', 'ㄹ', '말'],
          ['ㅂ', 'ㅏ', 'ㄹ', '발'],
          ['ㅅ', 'ㅏ', 'ㄹ', '살'],
          ['ㅇ', 'ㅏ', 'ㄹ', '알'],
          ['ㅈ', 'ㅏ', 'ㄹ', '잘'],
          ['ㅊ', 'ㅏ', 'ㄹ', '찰'],
          ['ㅋ', 'ㅏ', 'ㄹ', '칼'],
          ['ㅌ', 'ㅏ', 'ㄹ', '탈'],
          ['ㅍ', 'ㅏ', 'ㄹ', '팔'],
          ['ㅎ', 'ㅏ', 'ㄹ', '할'],
        ],
      },
      {
        id: 'kr-h2-u5',
        title: 'unit 5: ㅅ 받침 배우기',
        phonemes: ['받침ㅅ'],
        patterns: ['받침'],
        sampleWords: ['옷', '로봇', '비옷', '그릇'],
        blending: [
          ['ㄱ', 'ㅏ', 'ㅅ', '갓'],
          ['ㄴ', 'ㅏ', 'ㅅ', '낫'],
          ['ㄷ', 'ㅏ', 'ㅅ', '닷'],
          ['ㄹ', 'ㅏ', 'ㅅ', '랏'],
          ['ㅁ', 'ㅏ', 'ㅅ', '맛'],
          ['ㅂ', 'ㅏ', 'ㅅ', '밧'],
          ['ㅅ', 'ㅏ', 'ㅅ', '삿'],
          ['ㅇ', 'ㅏ', 'ㅅ', '앗'],
          ['ㅈ', 'ㅏ', 'ㅅ', '잣'],
          ['ㅊ', 'ㅏ', 'ㅅ', '찻'],
          ['ㅋ', 'ㅏ', 'ㅅ', '캇'],
          ['ㅌ', 'ㅏ', 'ㅅ', '탓'],
          ['ㅍ', 'ㅏ', 'ㅅ', '팟'],
          ['ㅎ', 'ㅏ', 'ㅅ', '핫'],
        ],
      },
      {
        id: 'kr-h2-u6',
        title: 'unit 6: ㅁ 받침 배우기',
        phonemes: ['받침ㅁ'],
        patterns: ['받침'],
        sampleWords: ['몸', '엄마', '염소', '구름'],
        blending: [
          ['ㄱ', 'ㅏ', 'ㅁ', '감'],
          ['ㄴ', 'ㅏ', 'ㅁ', '남'],
          ['ㄷ', 'ㅏ', 'ㅁ', '담'],
          ['ㄹ', 'ㅏ', 'ㅁ', '람'],
          ['ㅁ', 'ㅏ', 'ㅁ', '맘'],
          ['ㅂ', 'ㅏ', 'ㅁ', '밤'],
          ['ㅅ', 'ㅏ', 'ㅁ', '삼'],
          ['ㅇ', 'ㅏ', 'ㅁ', '암'],
          ['ㅈ', 'ㅏ', 'ㅁ', '잠'],
          ['ㅊ', 'ㅏ', 'ㅁ', '참'],
          ['ㅋ', 'ㅏ', 'ㅁ', '캄'],
          ['ㅌ', 'ㅏ', 'ㅁ', '탐'],
          ['ㅍ', 'ㅏ', 'ㅁ', '팜'],
          ['ㅎ', 'ㅏ', 'ㅁ', '함'],
        ],
      },
      {
        id: 'kr-h2-u7',
        title: 'unit 7: ㅂ 받침 배우기',
        phonemes: ['받침ㅂ'],
        patterns: ['받침'],
        sampleWords: ['집', '컵', '입술', '김밥'],
        blending: [
          ['ㄱ', 'ㅏ', 'ㅂ', '갑'],
          ['ㄴ', 'ㅏ', 'ㅂ', '납'],
          ['ㄷ', 'ㅏ', 'ㅂ', '답'],
          ['ㄹ', 'ㅏ', 'ㅂ', '랍'],
          ['ㅁ', 'ㅏ', 'ㅂ', '맙'],
          ['ㅂ', 'ㅏ', 'ㅂ', '밥'],
          ['ㅅ', 'ㅏ', 'ㅂ', '삽'],
          ['ㅇ', 'ㅏ', 'ㅂ', '압'],
          ['ㅈ', 'ㅏ', 'ㅂ', '잡'],
          ['ㅊ', 'ㅏ', 'ㅂ', '찹'],
          ['ㅋ', 'ㅏ', 'ㅂ', '캅'],
          ['ㅌ', 'ㅏ', 'ㅂ', '탑'],
          ['ㅍ', 'ㅏ', 'ㅂ', '팝'],
          ['ㅎ', 'ㅏ', 'ㅂ', '합'],
        ],
      },
    ],
  },
  {
    level: 'hangul3',
    name: '한글3: 쌍자음',
    description: 'ㄲ, ㄸ, ㅃ, ㅆ, ㅉ 쌍자음 학습',
    units: [
      {
        id: 'kr-h3-u1',
        title: 'unit 1: ㄲ 배우기',
        phonemes: ['ㄲ'],
        patterns: ['쌍자음'],
        sampleWords: ['꿀벌', '꼬끼오', '토끼', '코끼리'],
        blending: [
          ['ㄲ', 'ㅏ', '까'],
          ['ㄲ', 'ㅑ', '꺄'],
          ['ㄲ', 'ㅓ', '꺼'],
          ['ㄲ', 'ㅕ', '껴'],
          ['ㄲ', 'ㅗ', '꼬'],
          ['ㄲ', 'ㅛ', '꾜'],
          ['ㄲ', 'ㅜ', '꾸'],
          ['ㄲ', 'ㅠ', '뀨'],
          ['ㄲ', 'ㅡ', '끄'],
          ['ㄲ', 'ㅣ', '끼'],
        ],
      },
      {
        id: 'kr-h3-u2',
        title: 'unit 2: ㄸ 배우기',
        phonemes: ['ㄸ'],
        patterns: ['쌍자음'],
        sampleWords: ['떡국', '똑딱', '땅콩', '딸기'],
        blending: [
          ['ㄸ', 'ㅏ', '따'],
          ['ㄸ', 'ㅑ', '땨'],
          ['ㄸ', 'ㅓ', '떠'],
          ['ㄸ', 'ㅕ', '뗘'],
          ['ㄸ', 'ㅗ', '또'],
          ['ㄸ', 'ㅛ', '뚀'],
          ['ㄸ', 'ㅜ', '뚜'],
          ['ㄸ', 'ㅠ', '뜌'],
          ['ㄸ', 'ㅡ', '뜨'],
          ['ㄸ', 'ㅣ', '띠'],
        ],
      },
      {
        id: 'kr-h3-u3',
        title: 'unit 3: ㅃ 배우기',
        phonemes: ['ㅃ'],
        patterns: ['쌍자음'],
        sampleWords: ['오빠', '뽀뽀', '빨래', '아빠'],
        blending: [
          ['ㅃ', 'ㅏ', '빠'],
          ['ㅃ', 'ㅑ', '뺘'],
          ['ㅃ', 'ㅓ', '뻐'],
          ['ㅃ', 'ㅕ', '뼈'],
          ['ㅃ', 'ㅗ', '뽀'],
          ['ㅃ', 'ㅛ', '뾰'],
          ['ㅃ', 'ㅜ', '뿌'],
          ['ㅃ', 'ㅠ', '쀼'],
          ['ㅃ', 'ㅡ', '쁘'],
          ['ㅃ', 'ㅣ', '삐'],
        ],
      },
      {
        id: 'kr-h3-u4',
        title: 'unit 4: ㅆ 배우기',
        phonemes: ['ㅆ'],
        patterns: ['쌍자음'],
        sampleWords: ['씨앗', '새싹', '쓱싹', '썰매'],
        blending: [
          ['ㅆ', 'ㅏ', '싸'],
          ['ㅆ', 'ㅑ', '쌰'],
          ['ㅆ', 'ㅓ', '써'],
          ['ㅆ', 'ㅕ', '쎠'],
          ['ㅆ', 'ㅗ', '쏘'],
          ['ㅆ', 'ㅛ', '쑈'],
          ['ㅆ', 'ㅜ', '쑤'],
          ['ㅆ', 'ㅠ', '쓔'],
          ['ㅆ', 'ㅡ', '쓰'],
          ['ㅆ', 'ㅣ', '씨'],
        ],
      },
      {
        id: 'kr-h3-u5',
        title: 'unit 5: ㅉ 배우기',
        phonemes: ['ㅉ'],
        patterns: ['쌍자음'],
        sampleWords: ['찐빵', '짝꿍', '쫑긋', '쪽지'],
        blending: [
          ['ㅉ', 'ㅏ', '짜'],
          ['ㅉ', 'ㅑ', '쨔'],
          ['ㅉ', 'ㅓ', '쩌'],
          ['ㅉ', 'ㅕ', '쪄'],
          ['ㅉ', 'ㅗ', '쪼'],
          ['ㅉ', 'ㅛ', '쬬'],
          ['ㅉ', 'ㅜ', '쭈'],
          ['ㅉ', 'ㅠ', '쮸'],
          ['ㅉ', 'ㅡ', '쯔'],
          ['ㅉ', 'ㅣ', '찌'],
        ],
      },
    ],
  },
  {
    level: 'hangul4',
    name: '한글4: 복잡한 모음',
    description: 'ㅐ, ㅔ, ㅖ, ㅟ, ㅚ, ㅘ, ㅙ, ㅝ, ㅞ, ㅢ 복잡한 모음 학습',
    units: [
      {
        id: 'kr-h4-u1',
        title: 'unit 1: ㅐ, ㅔ 배우기',
        phonemes: ['ㅐ', 'ㅔ'],
        patterns: ['복잡한 모음'],
        sampleWords: ['고래', '동생', '레몬', '베개'],
        blending: [],
      },
      {
        id: 'kr-h4-u2',
        title: 'unit 2: ㅖ, ㅚ 배우기',
        phonemes: ['ㅖ', 'ㅚ'],
        patterns: ['복잡한 모음'],
        sampleWords: ['계란', '예절', '시계', '얘기'],
        blending: [],
      },
      {
        id: 'kr-h4-u3',
        title: 'unit 3: ㅟ, ㅢ 배우기',
        phonemes: ['ㅟ', 'ㅢ'],
        patterns: ['복잡한 모음'],
        sampleWords: ['참의', '열쇠', '생쥐', '가위'],
        blending: [],
      },
      {
        id: 'kr-h4-u4',
        title: 'unit 4: ㅘ, ㅙ 배우기',
        phonemes: ['ㅘ', 'ㅙ'],
        patterns: ['복잡한 모음'],
        sampleWords: ['과자', '사과', '화가', '횃불'],
        blending: [],
      },
      {
        id: 'kr-h4-u5',
        title: 'unit 5: ㅝ, ㅞ, ㅢ 배우기',
        phonemes: ['ㅝ', 'ㅞ', 'ㅢ'],
        patterns: ['복잡한 모음'],
        sampleWords: ['권투', '스웨터', '의자', '의사'],
        blending: [],
      },
    ],
  },
] as const;

export type PhonicsLanguage = 'english' | 'korean';
export type EnglishPhonicsLevel = (typeof ENGLISH_PHONICS_CURRICULUM)[number]['level'];
export type KoreanPhonicsLevel = (typeof KOREAN_PHONICS_CURRICULUM)[number]['level'];

/** 한글 숲 친구들 — 유닛별 기본 스토리 테마 + 등장 캐릭터 (12지신) */
export const KOREAN_UNIT_STORY_DEFAULTS: Record<
  string,
  { storyTheme: string; characterNames: string[] }
> = {
  // ── 한글1: 기본음절 ──
  'kr-h1-u1': {
    storyTheme:
      '글자 초원의 꽃잎 편지 — 장소: 글자 초원(Letter Meadow). 봄의 글자 초원에서 호돌이, 몽실이, 통통이가 소풍을 갔어요. 봄바람이 불더니 다섯 색깔의 꽃잎이 날아왔어요. 꽃잎마다 모음이 새겨져 있어요! "ㅏ!" "ㅓ!" 소리를 치니 꽃잎들이 빛나기 시작했어요. 10개의 기본 모음을 모두 모으면 숲이 무지개가 됩니다.',
    characterNames: ['호돌이', '몽실이', '통통이'],
  },
  'kr-h1-u2': {
    storyTheme:
      '속삭임 나무의 ㄱ 비밀 — 장소: 속삭임 나무(Whisper Tree). 호돌이와 깡총이가 숲에서 가장 오래된 속삭임 나무를 발견했어요. 나무껍질에 이상한 글자가 있어서 귀를 대니까 "그~" 소리가 들렸어요! "ㄱ!" 하며 소리를 따라하니 나무가 빛나며 "고기", "가구", "아기", "야구" 단어를 발견했어요!',
    characterNames: ['호돌이', '깡총이'],
  },
  'kr-h1-u3': {
    storyTheme:
      '글자 다리의 나무 계단 — 장소: 글자 다리(Letter Bridge). 호돌이와 멍멍이가 시냇물을 건너려고 글자 다리를 찾았어요. 다리 위 돌멩이에 "ㄴ"이 빛나며 소리가 났어요! 돌을 밟을 때마다 나~니 소리가 울리며 "나", "너", "누나", "누구야" 단어를 발견하여 다리를 건넜어요.',
    characterNames: ['호돌이', '멍멍이'],
  },
  'kr-h1-u4': {
    storyTheme:
      '바람 언덕의 달리기 대회 — 장소: 바람 언덕(Wind Hill). 달리기를 좋아하는 꼬꼬가 바람 언덕에서 달리기 대회를 열었어요. 달달이가 "히히힝!" 하면서 언덕을 달릴 때마다 발자국에서 ㄷ 글자가 나타나요! "두유", "도마", "기도", "구두" 단어로 오늘 학습 완성!',
    characterNames: ['달달이', '꼬꼬'],
  },
  'kr-h1-u5': {
    storyTheme:
      '별빛 연못의 물결 글자 — 장소: 별빛 연못(Starlight Pond). 달밤에 음메가 별빛 연못가에서 쉬고 있었어요. 통통이가 연못에 돌을 "퐁!" 하며 던지니 물결에서 ㄹ 모양의 빛나는 글자가 나타났어요! "오리", "너구리", "다리", "노루" 단어를 물결 위에서 발견했어요.',
    characterNames: ['통통이', '음메'],
  },
  'kr-h1-u6': {
    storyTheme:
      '꿀 폭포에서 찾은 ㅁ — 장소: 꿀 폭포(Honey Falls). 음메와 꿀꿀이가 꿀 폭포로 놀러 갔어요. 폭포에서 "뚝!" 물방울이 흘러와서 "ㅁ"이 나타나요! "머리", "모두", "모기", "거미" 단어를 폭포 소리로 익혔어요.',
    characterNames: ['음메', '꿀꿀이'],
  },
  'kr-h1-u7': {
    storyTheme:
      '구름 언덕의 바람 글자 — 장소: 구름 언덕(Cloud Hill). 구름을 좋아하는 몽실이가 구름 언덕에 올라갔어요. 구름들이 "ㅂ" 모양으로 변하기 시작했어요! 꿀꿀이와 함께 "바다", "비누", "나비", "두부"를 구름으로 그리며 배웠어요.',
    characterNames: ['꿀꿀이', '몽실이'],
  },
  'kr-h1-u8': {
    storyTheme:
      '속삭임 나무의 스르르 선생님 — 장소: 속삭임 나무(Whisper Tree). 조용한 스르르가 오늘은 선생님이에요! 나뭇잎이 바람에 스치는 소리 "스~" 에서 ㅅ을 발견했어요. "사자", "버스", "가수", "미소" — 스르르가 나뭇잎 글자를 새겨주었어요.',
    characterNames: ['스르르', '호돌이'],
  },
  'kr-h1-u9': {
    storyTheme:
      '메아리 동굴의 울림 소리 — 장소: 메아리 동굴(Echo Cave). 용용이가 호돌이를 데리고 메아리 동굴로 들어갔어요. "오~" 소리를 내자 동굴 벽에서 빛나는 ㅇ 글자가 나타났어요! "우주", "여우", "우유", "어부" 단어를 메아리로 배웠어요.',
    characterNames: ['용용이', '호돌이'],
  },
  'kr-h1-u10': {
    storyTheme:
      '글자 다리의 찍찍이 탐정 — 장소: 글자 다리(Letter Bridge). 찍찍이가 탐정 모자를 쓰고 글자 다리를 탐험했어요! 돌멩이 사이에 "ㅈ"이 숨어있었어요. 통통이와 함께 "지구", "지도", "자두", "모자"를 찾았어요.',
    characterNames: ['찍찍이', '통통이'],
  },
  'kr-h1-u11': {
    storyTheme:
      '햇살 언덕의 아침 탐험 — 장소: 햇살 언덕(Sunshine Hill). 꼬꼬가 "꼬끼오!" 하고 아침 해가 뜨자 호돌이를 깨웠어요. 이른 아침 햇살이 나무에 "ㅊ" 그림자를 그렸어요! "치마", "치즈", "마차", "기차" — 그림자를 따라 글자를 배웠어요.',
    characterNames: ['꼬꼬', '호돌이'],
  },
  'kr-h1-u12': {
    storyTheme:
      '나무 꼭대기의 깡총이 보물 — 장소: 속삭임 나무 꼭대기(Whisper Tree). 깡총이가 나무 꼭대기에서 잎사귀에 "ㅋ" 글자가 새겨져 있음을 발견! 달달이와 함께 잎을 흔들 때마다 "쿠키", "코코아", "마이크", "카드" 단어가 나타났어요.',
    characterNames: ['깡총이', '달달이'],
  },
  'kr-h1-u13': {
    storyTheme:
      '바람 언덕의 통통이와 달달이 — 장소: 바람 언덕(Wind Hill). 통통이와 달리기를 하러 바람 언덕에 갔어요. 달달이가 "히히힝!" 하며 달리면서 모래에 "ㅌ" 글자가 나타나요! "타조", "하트", "기타", "치타" — 달리면서 단어를 익혔어요.',
    characterNames: ['통통이', '달달이'],
  },
  'kr-h1-u14': {
    storyTheme:
      '꿀 폭포의 퐁당 글자 — 장소: 꿀 폭포(Honey Falls). 꿀꿀이와 찍찍이가 꿀 폭포에서 물놀이 중! 물방울이 "퐁!" 소리를 내자 "ㅍ"이 나타나요! "피자", "파리", "포도", "소파" — 물놀이 글자로 단어를 완성했어요.',
    characterNames: ['꿀꿀이', '찍찍이'],
  },
  'kr-h1-u15': {
    storyTheme:
      '별빛 연못의 호흡의 마지막 — 장소: 별빛 연못(Starlight Pond). 드디어 마지막 자음 "ㅎ"을 배울 날! 호돌이와 전체 친구들이 모두 별빛 연못에 모였어요. 별빛이 연못에 비추는 "ㅎ"이 나타나요! "하마", "호두", "휴지", "호수" — 모두가 함께 한글1을 완성했어요!',
    characterNames: ['호돌이', '스르르', '몽실이'],
  },
  // ── 한글2: 받침 ──
  'kr-h2-u1': {
    storyTheme:
      '글자 초원의 울림 받침 — 장소: 글자 초원(Letter Meadow). 가을 글자 초원에서 이상한 소리가 들렸어요. 꽃을 잡으면 "강, 능, 당…" 소리가 나요! "형!", "당!", "봉!" — ㅇ받침이 만들어지는 소리를 발견하며 "형", "풍당", "농구", "시장" 단어를 완성했어요.',
    characterNames: ['호돌이', '통통이', '찍찍이'],
  },
  'kr-h2-u2': {
    storyTheme:
      '속삭임 나무의 딱 소리 — 장소: 속삭임 나무(Whisper Tree). 나무를 두드리니 "딱!" 소리와 함께 ㄱ받침이 나타났어요! 깡총이와 꼬꼬가 나무 구멍에서 "학교", "축구", "악어", "탁구" 단어를 찾아냈어요.',
    characterNames: ['깡총이', '꼬꼬'],
  },
  'kr-h2-u3': {
    storyTheme:
      '글자 다리의 건너기 도전 — 장소: 글자 다리(Letter Bridge). 멍멍이가 ㄴ받침 돌들이 놓여진 다리를 건너는 도전을 열었어요! 돌을 밟을 때마다 "손, 눈, 건너…" 소리가 울리며 "손", "눈", "언니", "잔디" 단어를 완성했어요.',
    characterNames: ['멍멍이', '음메'],
  },
  'kr-h2-u4': {
    storyTheme:
      '별빛 연못의 달빛 글자 — 장소: 별빛 연못(Starlight Pond). 달달이와 스르르가 연못가를 걸었어요. 물결이 ㄹ받침 모양으로 변하며 빛났어요! "별", "달", "하늘", "가을" — 달빛으로 그린 글자를 배웠어요.',
    characterNames: ['달달이', '스르르'],
  },
  'kr-h2-u5': {
    storyTheme:
      '메아리 동굴의 굴소리 — 장소: 메아리 동굴(Echo Cave). 스르르와 음메가 동굴 깊은 곳을 탐험했어요. 동굴 끝에서 ㅅ받침 소리가 메아리로 울렸어요! "옷", "로봇", "비옷", "그릇" — 동굴 소리로 받침을 익혔어요.',
    characterNames: ['스르르', '음메'],
  },
  'kr-h2-u6': {
    storyTheme:
      '꿀 폭포의 달콤한 마무리 — 장소: 꿀 폭포(Honey Falls). 꿀꿀이가 "꿀꿀~" 하니까 폭포 밑에서 ㅁ받침이 나타났어요! "봄", "가람", "어름", "마음" — 모두 함께 달콤하게 한글2를 완성했어요! ★',
    characterNames: ['꿀꿀이', '음메', '호돌이'],
  },
  'kr-h2-u7': {
    storyTheme:
      '멍멍이의 김밥 가게 — 장소: 글자 초원(Letter Meadow). 멍멍이가 글자 초원에 김밥 가게를 열었어요! 입술 모양으로 "ㅂ" 소리를 내며 ㅂ받침이 들어간 단어를 배워요. 꿀꿀이와 호돌이가 함께 김밥 재료를 찾으며 한글2 받침 학습을 마무리합니다.',
    characterNames: ['호돌이', '멍멍이', '꿀꿀이'],
  },
};

/** 한글 자모 → 발음 텍스트 매핑 (자음: 자음+ㅡ, 모음: ㅇ+모음) */
export const KOREAN_PHONEME_MAP: Record<string, string> = {
  // 기본 자음 (14)
  ㄱ: '그',
  ㄴ: '느',
  ㄷ: '드',
  ㄹ: '르',
  ㅁ: '므',
  ㅂ: '브',
  ㅅ: '스',
  ㅇ: '으',
  ㅈ: '즈',
  ㅊ: '츠',
  ㅋ: '크',
  ㅌ: '트',
  ㅍ: '프',
  ㅎ: '흐',
  // 쌍자음 (5)
  ㄲ: '끄',
  ㄸ: '뜨',
  ㅃ: '쁘',
  ㅆ: '쓰',
  ㅉ: '쯔',
  // 모음 (21)
  ㅏ: '아',
  ㅐ: '애',
  ㅑ: '야',
  ㅒ: '얘',
  ㅓ: '어',
  ㅔ: '에',
  ㅕ: '여',
  ㅖ: '예',
  ㅗ: '오',
  ㅘ: '와',
  ㅙ: '왜',
  ㅚ: '외',
  ㅛ: '요',
  ㅜ: '우',
  ㅝ: '워',
  ㅞ: '웨',
  ㅟ: '위',
  ㅠ: '유',
  ㅡ: '으',
  ㅢ: '의',
  ㅣ: '이',
};

/** 한글 자모 텍스트를 TTS용 발음 텍스트로 변환 (예: "ㄱ ㅏ 가" → "그 아 가") */
export function mapKoreanPhonemeText(text: string): string {
  return text
    .split(/( +)/)
    .map((part) => KOREAN_PHONEME_MAP[part] ?? part)
    .join('');
}

export const WORKSHEET_TYPES = [
  { id: 'matching' as const, label: '매칭 (단어-그림)' },
  { id: 'fill-blank' as const, label: '빈칸 채우기' },
  { id: 'tracing' as const, label: '따라 쓰기' },
  { id: 'circle-sound' as const, label: '소리 찾기' },
] as const;

export const CHANT_TONES = [
  { id: 'cheerful' as const, label: '신나는' },
  { id: 'calm' as const, label: '잔잔한' },
  { id: 'hiphop' as const, label: '힙합' },
  { id: 'lullaby' as const, label: '자장가' },
] as const;

// === 카테고리 ===
export const STORYBOOK_CATEGORIES = ['자연 관찰', '기타'] as const;
export const PHONICS_CATEGORIES = ['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5'] as const;
