export const TARGET_AGES = ['4-5', '5-7', '7-8'] as const;
export type TargetAge = (typeof TARGET_AGES)[number];

export const ART_STYLES = [
  { id: 'modern-illustration', label: '현대 일러스트', prompt: 'Modern Illustration' },
  { id: 'watercolor', label: '수채화', prompt: 'Watercolor' },
  { id: 'cartoon', label: '카툰', prompt: 'Cartoon' },
  { id: 'traditional', label: '전통 동화책', prompt: 'Traditional Storybook' },
  { id: 'animation', label: '애니메이션', prompt: 'Animation' },
  { id: 'oil-painting', label: '유화', prompt: 'Oil Painting' },
  { id: 'pencil-sketch', label: '연필 스케치', prompt: 'Pencil Sketch' },
] as const;

export const ASPECT_RATIOS = ['16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '1:1'] as const;
export type AspectRatio = (typeof ASPECT_RATIOS)[number];

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: '영어' },
  { code: 'ja', label: '일본어' },
  { code: 'zh', label: '중국어' },
  { code: 'es', label: '스페인어' },
  { code: 'fr', label: '프랑스어' },
  { code: 'de', label: '독일어' },
] as const;

export const TTS_PROVIDERS = ['gemini', 'minimax', 'elevenlabs'] as const;
export type TtsProvider = (typeof TTS_PROVIDERS)[number];

export const TTS_VOICES = [
  { id: 'Leda', label: '레다', description: 'Youthful' },
  { id: 'Sulafat', label: '술라파트', description: 'Warm' },
  { id: 'Vindemiatrix', label: '빈데미아트릭스', description: 'Gentle' },
  { id: 'Achird', label: '아키르드', description: 'Friendly' },
  { id: 'Sadachbia', label: '사다크비아', description: 'Lively' },
  { id: 'Puck', label: '퍽', description: 'Upbeat' },
  { id: 'Kore', label: '코레', description: 'Firm' },
  { id: 'Achernar', label: '아케르나르', description: 'Soft' },
  { id: 'Zephyr', label: '제피르', description: 'Bright' },
  { id: 'Aoede', label: '아오에데', description: 'Breezy' },
] as const;

export const IMAGE_MODELS = [
  {
    id: 'gemini-2.5-flash-image',
    label: 'Nano Banana',
    description: '빠르고 효율적, 대량 생성에 적합',
  },
  {
    id: 'gemini-3.1-flash-image-preview',
    label: 'Nano Banana 2',
    description: '고효율, 빠른 속도 + 고품질',
  },
  {
    id: 'gemini-3-pro-image-preview',
    label: 'Nano Banana Pro',
    description: '최고 품질, 복잡한 지시 이해력 우수',
  },
  {
    id: 'imagen-4.0-fast-generate-001',
    label: 'Imagen 4 Fast',
    description: '텍스트→이미지 특화, 초고속 생성',
  },
  {
    id: 'imagen-4.0-generate-001',
    label: 'Imagen 4',
    description: '텍스트→이미지 특화, 고품질 2K',
  },
  {
    id: 'imagen-4.0-ultra-generate-001',
    label: 'Imagen 4 Ultra',
    description: '최고 품질 2K, 텍스트 렌더링 우수',
  },
] as const;
export type ImageModelId = (typeof IMAGE_MODELS)[number]['id'];

export const DEFAULT_IMAGE_MODEL = 'gemini-3.1-flash-image-preview' satisfies ImageModelId;

export const TEXT_MODELS = [
  { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', description: '빠르고 효율적' },
  { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro', description: '고품질, 정교한 추론' },
  { id: 'gemini-3-flash-preview', label: 'Gemini 3 Flash', description: '차세대 빠른 모델' },
  { id: 'gemini-3-pro-preview', label: 'Gemini 3 Pro', description: '차세대 고급 추론' },
  {
    id: 'gemini-3.1-pro-preview',
    label: 'Gemini 3.1 Pro',
    description: '최신, 100만 토큰 컨텍스트',
  },
] as const;
export type TextModelId = (typeof TEXT_MODELS)[number]['id'];
export const DEFAULT_TEXT_MODEL = 'gemini-2.5-flash' satisfies TextModelId;

export const MAX_IMAGE_HISTORY = 10;
export const MAX_FILE_SIZE_MB = 5;

// === Phonics 상수 ===

export const PHONICS_LANGUAGES = [
  { id: 'english' as const, label: '영어 파닉스' },
  { id: 'korean' as const, label: '한글 파닉스' },
] as const;

export const ENGLISH_PHONICS_CURRICULUM = [
  // === 1권: Single Letter Sounds — 알파벳 개별 음가 ===
  {
    level: 'book1',
    name: 'Book 1: Single Letter Sounds',
    description: '알파벳 Aa~Zz 개별 음가 (initial sounds)',
    units: [
      {
        id: 'en-b1-u1',
        title: 'Unit 1: Aa Bb Cc',
        phonemes: ['a', 'b', 'c'],
        patterns: ['initial sounds'],
        sampleWords: ['alligator', 'ant', 'apple', 'bag', 'bat', 'book', 'cap', 'cat', 'cup'],
      },
      {
        id: 'en-b1-u2',
        title: 'Unit 2: Dd Ee Ff',
        phonemes: ['d', 'e', 'f'],
        patterns: ['initial sounds'],
        sampleWords: ['desk', 'dog', 'duck', 'egg', 'elbow', 'elephant', 'fan', 'fish', 'fork'],
      },
      {
        id: 'en-b1-u3',
        title: 'Unit 3: Gg Hh Ii',
        phonemes: ['g', 'h', 'i'],
        patterns: ['initial sounds'],
        sampleWords: ['game', 'gift', 'gorilla', 'hand', 'hat', 'hippo', 'igloo', 'iguana', 'ink'],
      },
      {
        id: 'en-b1-u4',
        title: 'Unit 4: Jj Kk Ll',
        phonemes: ['j', 'k', 'l'],
        patterns: ['initial sounds'],
        sampleWords: ['jacket', 'jam', 'jet', 'key', 'king', 'kiwi', 'lamp', 'lemon', 'lion'],
      },
      {
        id: 'en-b1-u5',
        title: 'Unit 5: Mm Nn Oo',
        phonemes: ['m', 'n', 'o'],
        patterns: ['initial sounds'],
        sampleWords: ['map', 'melon', 'mouse', 'nest', 'net', 'nut', 'octopus', 'ostrich', 'ox'],
      },
      {
        id: 'en-b1-u6',
        title: 'Unit 6: Pp Qq Rr',
        phonemes: ['p', 'q', 'r'],
        patterns: ['initial sounds'],
        sampleWords: [
          'panda',
          'pen',
          'piano',
          'queen',
          'question',
          'quiet',
          'rabbit',
          'ring',
          'robot',
        ],
      },
      {
        id: 'en-b1-u7',
        title: 'Unit 7: Ss Tt Uu Vv',
        phonemes: ['s', 't', 'u', 'v'],
        patterns: ['initial sounds'],
        sampleWords: [
          'sand',
          'sock',
          'sun',
          'ten',
          'tiger',
          'top',
          'umbrella',
          'under',
          'up',
          'vase',
          'vest',
          'violin',
        ],
      },
      {
        id: 'en-b1-u8',
        title: 'Unit 8: Ww Xx Yy Zz',
        phonemes: ['w', 'x', 'y', 'z'],
        patterns: ['initial sounds'],
        sampleWords: [
          'watch',
          'watermelon',
          'window',
          'box',
          'fox',
          'six',
          'yacht',
          'yellow',
          'yo-yo',
          'zebra',
          'zero',
          'zoo',
        ],
      },
    ],
  },
  // === 2권: Short Vowels — 단모음 CVC ===
  {
    level: 'book2',
    name: 'Book 2: Short Vowels',
    description: '단모음 CVC 단어 (word families)',
    units: [
      {
        id: 'en-b2-u1',
        title: 'Unit 1: Short Vowel a (1)',
        phonemes: ['short-a'],
        patterns: ['_an', '_at'],
        sampleWords: ['can', 'fan', 'man', 'pan', 'bat', 'cat', 'hat', 'mat'],
      },
      {
        id: 'en-b2-u2',
        title: 'Unit 2: Short Vowel a (2)',
        phonemes: ['short-a'],
        patterns: ['_ap', '_ad', '_am'],
        sampleWords: ['cap', 'lap', 'map', 'tap', 'dad', 'sad', 'dam', 'jam'],
      },
      {
        id: 'en-b2-u3',
        title: 'Unit 3: Short Vowel i (1)',
        phonemes: ['short-i'],
        patterns: ['_ip', '_it', '_ix'],
        sampleWords: ['dip', 'hip', 'lip', 'rip', 'hit', 'sit', 'mix', 'six'],
      },
      {
        id: 'en-b2-u4',
        title: 'Unit 4: Short Vowel i (2)',
        phonemes: ['short-i'],
        patterns: ['_ib', '_id', '_ig', '_in'],
        sampleWords: ['bib', 'rib', 'kid', 'lid', 'dig', 'wig', 'fin', 'pin'],
      },
      {
        id: 'en-b2-u5',
        title: 'Unit 5: Short Vowel e',
        phonemes: ['short-e'],
        patterns: ['_et', '_ed', '_en'],
        sampleWords: ['jet', 'net', 'vet', 'wet', 'bed', 'red', 'hen', 'pen'],
      },
      {
        id: 'en-b2-u6',
        title: 'Unit 6: Short Vowel o',
        phonemes: ['short-o'],
        patterns: ['_og', '_op', '_ot', '_ox'],
        sampleWords: ['dog', 'log', 'hop', 'mop', 'hot', 'pot', 'box', 'fox'],
      },
      {
        id: 'en-b2-u7',
        title: 'Unit 7: Short Vowel u (1)',
        phonemes: ['short-u'],
        patterns: ['_ug', '_ub', '_up'],
        sampleWords: ['bug', 'hug', 'mug', 'rug', 'rub', 'tub', 'cup', 'pup'],
      },
      {
        id: 'en-b2-u8',
        title: 'Unit 8: Short Vowel u (2)',
        phonemes: ['short-u'],
        patterns: ['_un', '_ud', '_ut'],
        sampleWords: ['bun', 'fun', 'run', 'sun', 'bud', 'mud', 'cut', 'nut'],
      },
    ],
  },
  // === 3권: Long Vowels — 장모음 Magic e ===
  {
    level: 'book3',
    name: 'Book 3: Long Vowels (Magic e)',
    description: 'Magic e 장모음 CVCe 단어',
    units: [
      {
        id: 'en-b3-u1',
        title: 'Unit 1: Long Vowel a (1)',
        phonemes: ['long-a'],
        patterns: ['_ake', '_ape', '_ave'],
        sampleWords: ['bake', 'cake', 'lake', 'rake', 'cape', 'tape', 'cave', 'wave'],
      },
      {
        id: 'en-b3-u2',
        title: 'Unit 2: Long Vowel a (2)',
        phonemes: ['long-a'],
        patterns: ['_ame', '_ane', '_ase', '_ate'],
        sampleWords: ['game', 'name', 'came', 'lane', 'case', 'vase', 'date', 'gate'],
      },
      {
        id: 'en-b3-u3',
        title: 'Unit 3: Long Vowel i (1)',
        phonemes: ['long-i'],
        patterns: ['_ine', '_ike', '_ime'],
        sampleWords: ['line', 'nine', 'pine', 'vine', 'bike', 'hike', 'lime', 'time'],
      },
      {
        id: 'en-b3-u4',
        title: 'Unit 4: Long Vowel i (2)',
        phonemes: ['long-i'],
        patterns: ['_ide', '_ipe', '_ite', '_ive'],
        sampleWords: ['hide', 'ride', 'pipe', 'wipe', 'bite', 'kite', 'dive', 'five'],
      },
      {
        id: 'en-b3-u5',
        title: 'Unit 5: Long Vowel o (1)',
        phonemes: ['long-o'],
        patterns: ['_ose', '_ope', '_ote'],
        sampleWords: ['hose', 'nose', 'pose', 'rose', 'hope', 'rope', 'note', 'vote'],
      },
      {
        id: 'en-b3-u6',
        title: 'Unit 6: Long Vowel o (2)',
        phonemes: ['long-o'],
        patterns: ['_ole', '_ome', '_one'],
        sampleWords: ['hole', 'mole', 'pole', 'sole', 'dome', 'home', 'bone', 'cone'],
      },
      {
        id: 'en-b3-u7',
        title: 'Unit 7: Long Vowel u',
        phonemes: ['long-u'],
        patterns: ['_ube', '_ute', '_une', '_ule'],
        sampleWords: ['cube', 'tube', 'cute', 'mute', 'dune', 'June', 'tune', 'mule'],
      },
    ],
  },
  // === 4권: Consonant Blends & Digraphs ===
  {
    level: 'book4',
    name: 'Book 4: Consonant Blends & Digraphs',
    description: '자음군(bl, cr, st...) + 이중자음(ch, sh, th, ph, wh)',
    units: [
      {
        id: 'en-b4-u1',
        title: 'Unit 1: bl cl fl',
        phonemes: ['bl', 'cl', 'fl'],
        patterns: ['bl_', 'cl_', 'fl_'],
        sampleWords: [
          'black',
          'blade',
          'block',
          'blue',
          'clam',
          'clap',
          'cliff',
          'clock',
          'flag',
          'flame',
          'flap',
          'flute',
        ],
      },
      {
        id: 'en-b4-u2',
        title: 'Unit 2: br cr fr',
        phonemes: ['br', 'cr', 'fr'],
        patterns: ['br_', 'cr_', 'fr_'],
        sampleWords: [
          'brake',
          'brave',
          'brick',
          'bride',
          'crab',
          'crack',
          'crane',
          'crib',
          'frame',
          'frog',
          'front',
          'frost',
        ],
      },
      {
        id: 'en-b4-u3',
        title: 'Unit 3: gl pl sl',
        phonemes: ['gl', 'pl', 'sl'],
        patterns: ['gl_', 'pl_', 'sl_'],
        sampleWords: [
          'glass',
          'globe',
          'glove',
          'glue',
          'plane',
          'plant',
          'plate',
          'plum',
          'sled',
          'slice',
          'slide',
          'slim',
        ],
      },
      {
        id: 'en-b4-u4',
        title: 'Unit 4: dr pr tr',
        phonemes: ['dr', 'pr', 'tr'],
        patterns: ['dr_', 'pr_', 'tr_'],
        sampleWords: [
          'dragon',
          'dress',
          'drive',
          'drum',
          'press',
          'price',
          'print',
          'prize',
          'trace',
          'track',
          'truck',
          'tree',
        ],
      },
      {
        id: 'en-b4-u5',
        title: 'Unit 5: sm sn st sw',
        phonemes: ['sm', 'sn', 'st', 'sw'],
        patterns: ['sm_', 'sn_', 'st_', 'sw_'],
        sampleWords: [
          'smell',
          'smile',
          'smoke',
          'snack',
          'snake',
          'snore',
          'stone',
          'stop',
          'stove',
          'swan',
          'sweet',
          'swim',
        ],
      },
      {
        id: 'en-b4-u6',
        title: 'Unit 6: ng nk',
        phonemes: ['ng', 'nk'],
        patterns: ['_ng', '_nk'],
        sampleWords: [
          'bang',
          'fang',
          'king',
          'ring',
          'long',
          'song',
          'bank',
          'rank',
          'pink',
          'wink',
          'dunk',
          'junk',
        ],
      },
      {
        id: 'en-b4-u7',
        title: 'Unit 7: ch sh',
        phonemes: ['ch', 'sh'],
        patterns: ['ch_', '_ch', 'sh_', '_sh'],
        sampleWords: [
          'cherry',
          'chin',
          'bench',
          'branch',
          'catch',
          'shape',
          'ship',
          'shop',
          'brush',
          'fish',
          'wash',
        ],
      },
      {
        id: 'en-b4-u8',
        title: 'Unit 8: ph th wh',
        phonemes: ['ph', 'th', 'wh'],
        patterns: ['ph_', 'th_', 'wh_'],
        sampleWords: [
          'phone',
          'photo',
          'dolphin',
          'elephant',
          'thick',
          'thin',
          'bath',
          'teeth',
          'whale',
          'wheel',
          'whisper',
          'white',
        ],
      },
    ],
  },
  // === 5권: Double Letter Vowels & R-Controlled Vowels ===
  {
    level: 'book5',
    name: 'Book 5: Double Letter Vowels & R-Controlled',
    description: '이중모음(ee, ea, ai, ay, oi, oy, ow, ou) + R-통제 모음(ar, or, ir, er, ur)',
    units: [
      {
        id: 'en-b5-u1',
        title: 'Unit 1: ee ea (/iː/)',
        phonemes: ['ee', 'ea'],
        patterns: ['ee', 'ea'],
        sampleWords: [
          'bee',
          'feet',
          'green',
          'peel',
          'seed',
          'tree',
          'leaf',
          'meat',
          'peanut',
          'sea',
          'seal',
          'tea',
        ],
      },
      {
        id: 'en-b5-u2',
        title: 'Unit 2: oa ow (/oʊ/)',
        phonemes: ['oa', 'ow'],
        patterns: ['oa', 'ow'],
        sampleWords: [
          'boat',
          'coat',
          'goat',
          'road',
          'soap',
          'toast',
          'blow',
          'bowl',
          'pillow',
          'snow',
          'window',
        ],
      },
      {
        id: 'en-b5-u3',
        title: 'Unit 3: ai ay (/eɪ/)',
        phonemes: ['ai', 'ay'],
        patterns: ['ai', 'ay'],
        sampleWords: [
          'mail',
          'nail',
          'rail',
          'rain',
          'tail',
          'train',
          'clay',
          'gray',
          'hay',
          'play',
          'pray',
          'tray',
        ],
      },
      {
        id: 'en-b5-u4',
        title: 'Unit 4: oi oy (/ɔɪ/)',
        phonemes: ['oi', 'oy'],
        patterns: ['oi', 'oy'],
        sampleWords: [
          'boil',
          'coil',
          'coin',
          'foil',
          'oil',
          'point',
          'soil',
          'toilet',
          'boy',
          'joy',
          'soybean',
          'toy',
        ],
      },
      {
        id: 'en-b5-u5',
        title: 'Unit 5: ow ou (/aʊ/)',
        phonemes: ['ow', 'ou'],
        patterns: ['ow', 'ou'],
        sampleWords: [
          'brown',
          'clown',
          'cow',
          'crown',
          'gown',
          'owl',
          'blouse',
          'cloud',
          'count',
          'house',
          'mouse',
          'mouth',
        ],
      },
      {
        id: 'en-b5-u6',
        title: 'Unit 6: ir er ur (/ɜːr/)',
        phonemes: ['ir', 'er', 'ur'],
        patterns: ['ir', 'er', 'ur'],
        sampleWords: [
          'bird',
          'girl',
          'shirt',
          'skirt',
          'letter',
          'singer',
          'soccer',
          'teacher',
          'nurse',
          'purple',
          'purse',
          'turtle',
        ],
      },
      {
        id: 'en-b5-u7',
        title: 'Unit 7: ar or',
        phonemes: ['ar', 'or'],
        patterns: ['ar', 'or'],
        sampleWords: [
          'arm',
          'car',
          'card',
          'farmer',
          'park',
          'star',
          'cork',
          'corn',
          'fork',
          'horse',
          'north',
          'store',
        ],
      },
      {
        id: 'en-b5-u8',
        title: 'Unit 8: oo (/ʊ/ & /uː/)',
        phonemes: ['oo'],
        patterns: ['oo'],
        sampleWords: [
          'book',
          'cook',
          'foot',
          'hook',
          'look',
          'wood',
          'food',
          'goose',
          'moon',
          'pool',
          'spoon',
          'zoo',
        ],
      },
    ],
  },
] as const;

export const KOREAN_PHONICS_CURRICULUM = [
  {
    level: 'step1',
    name: 'Step 1: 자모음 소리',
    description: '자음 ㄱ~ㅎ + 모음 ㅏ~ㅣ 기본 소리',
    units: [
      {
        id: 'kr-s1-u1',
        title: '기본 자음: ㄱ ㄴ ㄷ ㄹ ㅁ',
        phonemes: ['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ'],
        patterns: ['자음'],
        sampleWords: ['가방', '나무', '다리', '라면', '마을'],
      },
      {
        id: 'kr-s1-u2',
        title: '기본 자음: ㅂ ㅅ ㅇ ㅈ ㅎ',
        phonemes: ['ㅂ', 'ㅅ', 'ㅇ', 'ㅈ', 'ㅎ'],
        patterns: ['자음'],
        sampleWords: ['바다', '사과', '아이', '자동차', '하늘'],
      },
      {
        id: 'kr-s1-u3',
        title: '기본 모음: ㅏ ㅓ ㅗ ㅜ ㅡ ㅣ',
        phonemes: ['ㅏ', 'ㅓ', 'ㅗ', 'ㅜ', 'ㅡ', 'ㅣ'],
        patterns: ['모음'],
        sampleWords: ['아이', '여우', '오리', '우유', '으름', '이불'],
      },
    ],
  },
  {
    level: 'step2',
    name: 'Step 2: 기본 음절',
    description: '자+모 결합, 받침 없는 글자',
    units: [
      {
        id: 'kr-s2-u1',
        title: '가나다: 받침 없는 글자',
        phonemes: ['가', '나', '다', '라', '마'],
        patterns: ['자+모 결합'],
        sampleWords: ['고기', '나비', '두부', '머리', '바지', '소리', '여기', '이리'],
      },
      {
        id: 'kr-s2-u2',
        title: '기본 단어 읽기',
        phonemes: ['바', '사', '아', '자', '하'],
        patterns: ['2음절 단어'],
        sampleWords: ['가구', '나무', '바다', '사자', '토끼', '하마', '고래', '거미'],
      },
    ],
  },
  {
    level: 'step3',
    name: 'Step 3: 받침과 복합 음절',
    description: '받침(ㄱ,ㄴ,ㄹ,ㅁ...), 겹받침, 이중모음',
    units: [
      {
        id: 'kr-s3-u1',
        title: '기본 받침: ㄱ ㄴ ㄹ ㅁ ㅂ ㅅ ㅇ',
        phonemes: ['받침ㄱ', '받침ㄴ', '받침ㄹ', '받침ㅁ', '받침ㅂ', '받침ㅅ', '받침ㅇ'],
        patterns: ['받침'],
        sampleWords: ['국', '손', '달', '밤', '밥', '못', '강', '공'],
      },
      {
        id: 'kr-s3-u2',
        title: '이중모음: ㅐ ㅔ ㅘ ㅙ ㅚ ㅝ ㅞ ㅟ ㅢ',
        phonemes: ['ㅐ', 'ㅔ', 'ㅘ', 'ㅙ', 'ㅚ', 'ㅝ', 'ㅞ', 'ㅟ', 'ㅢ'],
        patterns: ['이중모음'],
        sampleWords: ['개', '새', '게', '세계', '사과', '화가', '의사', '귀', '쥐'],
      },
      {
        id: 'kr-s3-u3',
        title: '쌍자음: ㄲ ㄸ ㅃ ㅆ ㅉ',
        phonemes: ['ㄲ', 'ㄸ', 'ㅃ', 'ㅆ', 'ㅉ'],
        patterns: ['쌍자음'],
        sampleWords: ['까치', '떡', '뿔', '쏘다', '짜다', '꽃', '빵', '씨앗'],
      },
    ],
  },
] as const;

export type PhonicsLanguage = 'english' | 'korean';
export type EnglishPhonicsLevel = (typeof ENGLISH_PHONICS_CURRICULUM)[number]['level'];
export type KoreanPhonicsLevel = (typeof KOREAN_PHONICS_CURRICULUM)[number]['level'];

export const WORKSHEET_TYPES = [
  { id: 'matching' as const, label: '매칭 (단어-그림)' },
  { id: 'fill-blank' as const, label: '빈칸 채우기' },
  { id: 'tracing' as const, label: '따라 쓰기' },
  { id: 'circle-sound' as const, label: '소리 찾기' },
] as const;

export const CHANT_TONES = [
  { id: 'cheerful' as const, label: '신나는' },
  { id: 'calm' as const, label: '잔잔한' },
  { id: 'hiphop' as const, label: '힙합' },
  { id: 'lullaby' as const, label: '자장가' },
] as const;

// === 카테고리 ===
export const STORYBOOK_CATEGORIES = ['자연 관찰', '기타'] as const;
export const PHONICS_CATEGORIES = ['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5'] as const;
