"""Build complete unicode-ranged web assets, not a title-only subset font.

A small common-title shard improves initial loading; every remaining supported
character is retained in separately loaded shards. Original and OFL sources stay
distinct in the manifest. Run only after the global coverage build finishes.
"""
import json, hashlib, shutil, argparse
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools import subset
from build import ROOT

PROJECT=ROOT.parents[2]
DATA=Path('D:/ComfyUI-output/library-clean-covers-20261006')
SAMPLES={
 'ko':'호리와 엄마의 무지개 꼬리 · 잠자는 숲속의 공주',
 'en':'The Little Mermaid & The Wonderful Wizard of Oz',
 'ja':'赤ずきん・眠れる森の美女・かわいい動物たち',
 'zh':'小红帽与大灰狼・海底动物的奇妙世界',
 'es':'El pequeño príncipe y el árbol mágico',
 'fr':'La forêt enchantée et le petit garçon',
 'de':'Das süße Häschen und die große Überraschung',
 'vi':'Cô bé quàng khăn đỏ và những người bạn',
 'th':'เจ้าหญิงน้อยกับเพื่อนในป่าแสนมหัศจรรย์',
 'ms':'Pengembaraan si kecil di dalam hutan',
 'id':'Petualangan kelinci kecil dan teman-temannya',
}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ranges(cps):
 out=[];start=last=None
 for cp in sorted(cps):
  if start is None:start=last=cp
  elif cp==last+1:last=cp
  else:out.append((start,last));start=last=cp
 if start is not None:out.append((start,last))
 return ','.join(f'U+{a:X}'+(f'-{b:X}' if a!=b else '') for a,b in out)
def main(source):
 report=json.loads((source/'coverage.json').read_text(encoding='utf8'))
 assert not report['validation']['missingTitles']
 out=PROJECT/'packages/client/public/fonts/tangobook-story-hand/0.4.0'
 out.mkdir(parents=True,exist_ok=True)
 rows=json.loads((DATA/'all-list.json').read_text(encoding='utf8'))['data']
 common=set(ord(c) for b in rows for s in [b.get('title',''),*(b.get('titleTranslations') or {}).values()] for c in s)
 common.update(ord(c) for s in SAMPLES.values() for c in s)
 manifest={'version':'0.4.0','status':'built-awaiting-browser-review','sourceCoverage':report,'files':[],'all11Languages':list(SAMPLES),'sampleText':SAMPLES}
 rules=[]
 for key,group in report['groups'].items():
  cps=set(group['codepoints']);chunks=[]
  if key in ('Chinese','Japanese'):
   frequent=cps&common
   if frequent:chunks.append(('common',frequent))
   remaining=cps-frequent
   for block in sorted({cp//2048 for cp in remaining}):chunks.append((f'{block:03d}',{cp for cp in remaining if cp//2048==block}))
  else:chunks=[('all',cps)]
  written=set()
  for label,chars in chunks:
   font=TTFont(source/(key+'.ttf'));opt=subset.Options();opt.recalc_timestamp=False;opt.name_IDs=['*'];opt.name_legacy=True;opt.name_languages=['*']
   sub=subset.Subsetter(options=opt);sub.populate(unicodes=chars);sub.subset(font)
   names={3:key+'-TangoBookStoryHand-0.4.0',5:'Version 0.400',10:'Complete supported unicode scope; original TangoBook Korean and lettering with licensed Noto compatibility glyphs.'}
   for rec in font['name'].names:
    if rec.nameID in names:rec.string=names[rec.nameID].encode(rec.getEncoding())
   file=out/(key.lower()+'-'+label+'.woff2');font.flavor='woff2';font.recalcTimestamp=False;font.save(file)
   actual=set(font.getBestCmap());assert actual==chars,(key,label,len(actual),len(chars));written|=actual
   url='/fonts/tangobook-story-hand/0.4.0/'+file.name
   rules.append('@font-face{font-family:"'+group['family']+'";font-style:normal;font-weight:400;font-display:swap;src:url("'+url+'") format("woff2");unicode-range:'+ranges(actual)+';}')
   manifest['files'].append({'file':file.name,'group':key,'sha256':sha(file),'bytes':file.stat().st_size,'codepoints':sorted(actual),'family':group['family']})
  assert written==cps
  print(key,len(chunks),len(written),flush=True)
 for name in ('OFL-CJK.txt','OFL-Noto.txt','sources.json'):shutil.copyfile(DATA/'font-sources'/name,out/name)
 (out/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf8')
 css=PROJECT/'packages/client/src/lib/cover-title-fonts.css';css.write_text('/* Generated by build_web_global.py. Complete unicode scopes; see public/fonts/tangobook-story-hand/0.4.0/manifest.json. */\n'+'\n'.join(rules)+'\n',encoding='utf8')
 body=[]
 for lang,text in SAMPLES.items():
  family='TangoBook Story Hand Global Japanese' if lang=='ja' else 'TangoBook Story Hand Global'
  body.append(f'<section lang="{lang}" data-lang="{lang}"><label>{lang}</label><div class="large" style="font-family:\'{family}\',\'TangoBook Story Hand Global\'">{text}</div><div class="small" style="font-family:\'{family}\',\'TangoBook Story Hand Global\'">{text}</div></section>')
 html='<!doctype html><meta charset="utf-8"><title>TangoBook complete language font proof</title><style>'+''.join(rules)+'body{background:#fff9ee;color:#493528;margin:24px}section{margin:18px 0;padding:12px;border:1px solid #dbc9b8}.large{font-size:38px;line-height:1.65}.small{font-size:18px;line-height:1.65}label{font:14px sans-serif}</style><h1>11-language actual webfont proof</h1>'+''.join(body)
 (PROJECT/'packages/client/public/cover-font-proof.html').write_text(html,encoding='utf8')
 print(json.dumps({'assets':len(manifest['files']),'bytes':sum(f['bytes'] for f in manifest['files']),'missingTitles':0}))
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--source',type=Path,default=ROOT/'dist-global-bold-preview');main(parser.parse_args().source)
