import type { WeeklyReportData } from '../types/analytics';

export function buildWeeklyReportHtml(data: WeeklyReportData): string {
  const { projectName, period, analytics, content, keywords } = data;

  return `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<title>${projectName} 주간 보고서 (${period.start} ~ ${period.end})</title>
<style>
  body { font-family: 'Noto Sans KR', sans-serif; max-width: 800px; margin: 0 auto; padding: 32px; color: #1a1a18; font-size: 14px; line-height: 1.6; }
  h1 { font-size: 24px; font-weight: 900; margin-bottom: 4px; }
  .period { color: #6b6960; font-size: 13px; margin-bottom: 24px; }
  .section { margin-bottom: 32px; }
  .section-title { font-size: 16px; font-weight: 900; border-bottom: 2px solid #0F6E56; padding-bottom: 4px; margin-bottom: 12px; }
  .stat-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 16px; }
  .stat-card { background: #f5f5f3; border-radius: 10px; padding: 14px; text-align: center; }
  .stat-num { font-size: 24px; font-weight: 900; }
  .stat-lbl { font-size: 11px; color: #6b6960; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { background: #0F6E56; color: white; padding: 8px; text-align: left; font-size: 11px; }
  td { padding: 8px; border-bottom: 1px solid #e8e6e0; }
  tr:hover td { background: #f9f9f7; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 700; }
  .badge-published { background: #E8F5F0; color: #0F6E56; }
  .badge-draft { background: #F5F5F3; color: #6b6960; }
  footer { margin-top: 40px; text-align: center; font-size: 11px; color: #9b9890; border-top: 1px solid #e8e6e0; padding-top: 16px; }
</style>
</head>
<body>
<h1>${projectName} 주간 보고서</h1>
<div class="period">${period.start} ~ ${period.end}</div>

${
  analytics
    ? `
<div class="section">
  <div class="section-title">사이트 트래픽</div>
  <div class="stat-grid">
    <div class="stat-card">
      <div class="stat-num">${analytics.sessions.toLocaleString()}</div>
      <div class="stat-lbl">세션</div>
    </div>
    <div class="stat-card">
      <div class="stat-num">${analytics.users.toLocaleString()}</div>
      <div class="stat-lbl">사용자</div>
    </div>
    <div class="stat-card">
      <div class="stat-num">${analytics.pageviews.toLocaleString()}</div>
      <div class="stat-lbl">페이지뷰</div>
    </div>
    <div class="stat-card">
      <div class="stat-num">${(analytics.bounceRate * 100).toFixed(1)}%</div>
      <div class="stat-lbl">이탈률</div>
    </div>
  </div>
  ${
    analytics.trafficSources.length > 0
      ? `
  <table>
    <thead><tr><th>트래픽 소스</th><th>세션</th><th>비중</th></tr></thead>
    <tbody>${analytics.trafficSources
      .map(
        (s) =>
          `<tr><td>${s.channel}</td><td>${s.sessions.toLocaleString()}</td><td>${s.percentage}%</td></tr>`
      )
      .join('')}</tbody>
  </table>`
      : ''
  }
</div>`
    : '<div class="section"><p style="color:#6b6960">GA4 미연동 — 프로젝트 설정에서 연결하세요</p></div>'
}

<div class="section">
  <div class="section-title">콘텐츠 현황</div>
  <div class="stat-grid" style="grid-template-columns: repeat(3, 1fr);">
    <div class="stat-card">
      <div class="stat-num">${content.totalCreated}</div>
      <div class="stat-lbl">이번 주 작성</div>
    </div>
    <div class="stat-card">
      <div class="stat-num">${content.totalPublished}</div>
      <div class="stat-lbl">발행 완료</div>
    </div>
    <div class="stat-card">
      <div class="stat-num">${content.byChannel.map((c) => c.count).reduce((a, b) => a + b, 0)}</div>
      <div class="stat-lbl">채널 콘텐츠</div>
    </div>
  </div>
  ${
    content.byChannel.length > 0
      ? `
  <table>
    <thead><tr><th>채널</th><th>콘텐츠 수</th></tr></thead>
    <tbody>${content.byChannel
      .map((c) => `<tr><td>${c.channel}</td><td>${c.count}</td></tr>`)
      .join('')}</tbody>
  </table>`
      : ''
  }
  ${
    content.recentItems.length > 0
      ? `
  <div style="margin-top:12px;">
    <table>
      <thead><tr><th>제목</th><th>채널</th><th>상태</th></tr></thead>
      <tbody>${content.recentItems
        .map(
          (item) =>
            `<tr><td>${item.title}</td><td>${item.channel}</td><td><span class="badge ${item.status === 'published' ? 'badge-published' : 'badge-draft'}">${item.status}</span></td></tr>`
        )
        .join('')}</tbody>
    </table>
  </div>`
      : ''
  }
</div>

${
  keywords
    ? `
<div class="section">
  <div class="section-title">키워드 현황</div>
  <p>추적 키워드: <strong>${keywords.tracked}개</strong></p>
  ${keywords.goldenKeywords.length > 0 ? `<p>황금 키워드: ${keywords.goldenKeywords.map((k) => `<span style="background:#FFF8E8;padding:2px 8px;border-radius:10px;font-size:12px;font-weight:700;color:#BA7517;margin-right:4px;">${k}</span>`).join('')}</p>` : ''}
</div>`
    : ''
}

<footer>
  Generated by <strong>ContentFlow</strong> · ${new Date().toISOString().slice(0, 10)}
</footer>
</body>
</html>`;
}
