"""One MiniMax shot: anatomical right-hand final tile, then smile toward filming mom."""
import pathlib,json,shutil
repo=pathlib.Path(__file__).resolve().parents[2]
root=pathlib.Path('D:/ComfyUI-output/virtual-parenting-20261006/tango-turnaround')
keys=root/'keyframes';keys.mkdir(parents=True,exist_ok=True)
generated=pathlib.Path('C:/Users/101024/.codex/generated_images/01a110d5-935b-7ff1-b313-4fb9a025ea65')
sources={'complete':'exec-1bbe9da5-dd5c-4735-9114-65df5750968c.png','look-back':'exec-8dca5b02-a426-42d2-a6be-f2df78270271.png','start':'exec-d2bdcca6-b304-4843-a598-0c45985a4304.png'}
for name,file in sources.items():shutil.copy2(generated/file,keys/f'{name}.png')
prompt='''One continuous candid real smartphone video, identical fixed over-the-shoulder camera from first to last frame, no cut, no zoom, no pan. Same small seated boy and home. He is viewed from BEHIND. The acting RIGHT hand is the hand on the RIGHT SIDE OF THE IMAGE next to the tablet. That existing image-right hand ALREADY holds the single narrow yellow vowel tile in the first photograph. During seconds 0 to 2.5, ONLY THAT SAME RIGHT HAND gently lowers its held tile onto the empty studs immediately below the square tile in the right-hand syllable group, matching the final photograph exactly. Place, release fingers, and move the same connected hand back onto its image-right resting spot on the desk. The image-left hand stays still at the front-left desk edge throughout; it must never reach for the tile. There are exactly two existing arms and two hands, no third hand and no new sleeve. After the placement is complete, pause naturally looking at the tablet, then during seconds 3.5 to 6.5 rotate his head and upper shoulders slightly back over the shoulder nearest the camera, look directly up at his mother filming him, and smile with genuine child delight and a few small teeth visible, matching the final photograph. Keep both hands DOWN at the tabletop. Do not raise arms, stand up, clap or turn the entire chair. Natural anatomically possible glance back with small upper torso rotation, no neck twist. End holding that happy eye contact and smile. The table edges, seam, legs, chair, shelf, books, window, floor, all spare tiles, portrait tablet and orange mirror remain completely stationary and unchanged in the entire shot. The three already placed tiles never move; the count changes from three to four ONLY by lowering the one physical held tile. All four finished tile positions match the final photograph exactly and remain fixed afterward, with the final horizontal vowel directly BELOW the second square consonant in the same column. Tablet screen remains the same furniture word and chair/drawer picture. No floating objects, no text graphics, no overlays, no subtitles, no scene changes. Real cotton, skin, hair, warm natural daylight, unposed real home video.'''
g=json.loads((repo/'scripts/virtual-parenting/tango-gagu-fixed-workflow.json').read_text(encoding='utf-8'))
for node,file in [('50','start.png'),('51','look-back.png')]:
 name='tango_turnaround_'+file;shutil.copy2(keys/file,pathlib.Path('C:/ComfyUI_windows_portable/ComfyUI/input')/name);g[node]['inputs']['image']=name
g['10']['inputs'].update(prompt=prompt,width=640,height=800,length=196)
g['23']['inputs']['noise_seed']=202610502
g['41']['inputs']['filename_prefix']='tango_turnaround/final-tile-smile'
(root/'workflow.json').write_text(json.dumps(g,ensure_ascii=False,indent=2),encoding='utf-8')
(root/'prompt.txt').write_text(prompt,encoding='utf-8')
(root/'source-ledger.json').write_text(json.dumps(dict(native='family-home-tango-sequence.blend',fixed_native='native/fixed-camera-turnaround.blend',photo_tool='imagegen built-in',photo_sources=sources,first_photo_rejected='exec-4a54870e-9889-4ed9-bbde-49ee53010382.png: missing fourth tile',cancelled_prompt='a8630196-c4da-414a-b863-7c92f82430fb: user rejected image-left acting hand',rejected_start='exec-9f159f7d-c4f7-498a-82b3-61cfc978bfb3.png: image-left hand acts',notes=['User corrected acting hand to IMAGE-RIGHT; image-left remains resting','Imagegen reinterprets geometry; exact CAD dimensions not guaranteed','Same corrected complete photograph locally edited for start and end']),ensure_ascii=False,indent=2),encoding='utf-8')
print(root/'workflow.json')
