/** Missing library display titles for existing Korean collections. Stored translations win. */
const rows = [
  ['반쪽이', 'The Half-Boy', 'Cậu bé một nửa', '半边儿', 'เด็กชายครึ่งตัว'],
  [
    '두더지의 혼인',
    'The Mole’s Wedding',
    'Đám cưới của chuột chũi',
    '鼹鼠的婚礼',
    'งานแต่งงานของตัวตุ่น',
  ],
  [
    '좁쌀 한 톨로 장가든 총각',
    'The Bachelor Who Married with a Grain of Millet',
    'Chàng trai cưới vợ nhờ một hạt kê',
    '靠一粒小米娶妻的小伙子',
    'ชายหนุ่มที่แต่งงานได้ด้วยข้าวฟ่างหนึ่งเมล็ด',
  ],
  ['구렁덩덩 새선비', 'The Serpent Husband', 'Chàng rắn', '蛇郎君', 'เจ้าบ่าวงู'],
  [
    '복 타러 간 총각',
    'The Boy Who Sought His Fortune',
    'Chàng trai đi tìm vận may',
    '寻找福气的小伙子',
    'ชายหนุ่มออกตามหาโชค',
  ],
  ['호랑이 형님', 'The Tiger Brother', 'Anh hổ', '老虎哥哥', 'พี่ชายเสือ'],
  ['은혜 갚은 두꺼비', 'The Grateful Toad', 'Cóc trả ơn', '报恩的蟾蜍', 'คางคกตอบแทนบุญคุณ'],
  ['개와 고양이', 'The Dog and the Cat', 'Chó và mèo', '狗和猫', 'สุนัขกับแมว'],
  ['신기한 항아리', 'The Magic Jar', 'Chiếc chum kỳ diệu', '神奇的坛子', 'ไหหัศจรรย์'],
  ['자린고비', 'The Miser', 'Ông lão keo kiệt', '吝啬鬼', 'ชายผู้ขี้เหนียว'],
  ['요술 맷돌', 'The Magic Millstone', 'Cối xay thần kỳ', '神奇的石磨', 'โม่วิเศษ'],
  [
    '도깨비 감투',
    'The Goblin’s Magic Hat',
    'Chiếc mũ thần của yêu tinh',
    '鬼怪的隐身帽',
    'หมวกวิเศษของโทแกบี',
  ],
  ['훨훨 간다', 'Off They Go', 'Bay đi nào', '飞呀飞', 'บินไปเลย'],
  [
    '떡보와 사신',
    'The Rice-Cake Eater and the Envoy',
    'Người mê bánh gạo và sứ giả',
    '爱吃年糕的人和使者',
    'คนชอบกินต็อกกับทูต',
  ],
  ['서동요', 'The Ballad of Seodong', 'Bài ca Seodong', '薯童谣', 'เพลงของซอดง'],
  ['단군 이야기', 'The Story of Dangun', 'Chuyện về Dangun', '檀君的故事', 'เรื่องของทันกุน'],
  ['토끼의 재판', 'The Rabbit’s Judgment', 'Phiên xử của thỏ', '兔子的审判', 'การตัดสินของกระต่าย'],
  ['삼년고개', 'The Three-Year Hill', 'Đồi ba năm', '三年坡', 'เนินสามปี'],
  ['심청전', 'The Tale of Sim Cheong', 'Chuyện nàng Sim Cheong', '沈清传', 'เรื่องของชิมชอง'],
  [
    '바보 온달과 평강공주',
    'Ondal and Princess Pyeonggang',
    'Ondal và công chúa Pyeonggang',
    '傻瓜温达与平冈公主',
    'อนดัลกับเจ้าหญิงพยองกัง',
  ],
  [
    '임금님 귀는 당나귀 귀',
    'The King Has Donkey Ears',
    'Nhà vua có tai lừa',
    '国王长着驴耳朵',
    'พระราชามีหูลา',
  ],
  [
    '소가 된 게으름뱅이',
    'The Lazy Fellow Who Became an Ox',
    'Anh chàng lười biến thành bò',
    '变成牛的懒汉',
    'คนขี้เกียจที่กลายเป็นวัว',
  ],
  [
    '재주 많은 삼형제',
    'The Three Talented Brothers',
    'Ba anh em tài giỏi',
    '本领高强的三兄弟',
    'สามพี่น้องผู้มีความสามารถ',
  ],
  ['우렁각시', 'The Snail Maiden', 'Cô gái ốc', '田螺姑娘', 'สาวน้อยหอยขม'],
  ['의좋은 형제', 'The Loving Brothers', 'Hai anh em hòa thuận', '和睦的兄弟', 'พี่น้องผู้รักกัน'],
  [
    '견우와 직녀',
    'The Cowherd and the Weaver',
    'Ngưu Lang và Chức Nữ',
    '牛郎织女',
    'หนุ่มเลี้ยงวัวกับสาวทอผ้า',
  ],
  [
    '젊어지는 샘물',
    'The Spring of Youth',
    'Suối hồi xuân',
    '返老还童的泉水',
    'น้ำพุคืนความเยาว์วัย',
  ],
  [
    '은혜 갚은 까치',
    'The Grateful Magpie',
    'Chim ác là trả ơn',
    '报恩的喜鹊',
    'นกกางเขนตอบแทนบุญคุณ',
  ],
  [
    '호랑이와 곶감',
    'The Tiger and the Dried Persimmon',
    'Hổ và quả hồng khô',
    '老虎和柿饼',
    'เสือกับลูกพลับแห้ง',
  ],
  ['콩쥐 팥쥐', 'Kongjwi and Patjwi', 'Kongjwi và Patjwi', '孔姬与豆姬', 'คงจวีกับพัดจวี'],
  [
    '해와 달이 된 오누이',
    'The Siblings Who Became the Sun and Moon',
    'Hai anh em trở thành mặt trời và mặt trăng',
    '变成太阳和月亮的兄妹',
    'พี่น้องที่กลายเป็นดวงอาทิตย์และดวงจันทร์',
  ],
  [
    '선녀와 나무꾼',
    'The Fairy and the Woodcutter',
    'Tiên nữ và chàng tiều phu',
    '仙女与樵夫',
    'นางฟ้ากับคนตัดไม้',
  ],
  [
    '말 안 듣는 청개구리',
    'The Disobedient Green Frog',
    'Chú ếch xanh không nghe lời',
    '不听话的青蛙',
    'กบเขียวที่ไม่เชื่อฟัง',
  ],
  [
    '혹부리 영감',
    'The Old Man with the Lump',
    'Ông lão có bướu',
    '长瘤的老爷爷',
    'คุณตาผู้มีปุ่มที่แก้ม',
  ],
  [
    '금도끼 은도끼',
    'The Gold Axe and the Silver Axe',
    'Rìu vàng và rìu bạc',
    '金斧头与银斧头',
    'ขวานทองกับขวานเงิน',
  ],
  ['토끼와 자라', 'The Rabbit and the Turtle', 'Thỏ và ba ba', '兔子与鳖', 'กระต่ายกับตะพาบน้ำ'],
  [
    '팥죽 할멈과 호랑이',
    'The Red-Bean Porridge Granny and the Tiger',
    'Bà lão nấu cháo đậu đỏ và hổ',
    '红豆粥婆婆与老虎',
    'คุณยายโจ๊กถั่วแดงกับเสือ',
  ],
  [
    '도깨비방망이',
    'The Goblin’s Magic Club',
    'Chiếc gậy thần của yêu tinh',
    '鬼怪的魔棒',
    'กระบองวิเศษของโทแกบี',
  ],
  [
    '방귀쟁이 며느리',
    'The Farting Daughter-in-Law',
    'Nàng dâu hay đánh rắm',
    '爱放屁的儿媳妇',
    'ลูกสะใภ้จอมผายลม',
  ],
  ['흥부와 놀부', 'Heungbu and Nolbu', 'Heungbu và Nolbu', '兴夫与孬夫', 'ฮึงบูกับนลบู'],
  ['편지 배달 왔어요', 'The Mail Is Here', 'Thư đến rồi', '来送信啦', 'จดหมายมาแล้ว'],
  ['우주로 슝', 'Zoom into Space', 'Vút vào vũ trụ', '嗖，飞向太空', 'พุ่งสู่อวกาศ'],
  [
    '바다 위 큰 집',
    'A Big House on the Sea',
    'Ngôi nhà lớn trên biển',
    '海上的大房子',
    'บ้านหลังใหญ่บนทะเล',
  ],
  [
    '깨끗깨끗 청소차',
    'The Cleaning Truck',
    'Xe quét dọn sạch sẽ',
    '干干净净的清扫车',
    'รถทำความสะอาด',
  ],
  [
    '빙글빙글 프로펠러',
    'The Spinning Propeller',
    'Cánh quạt quay tròn',
    '转呀转的螺旋桨',
    'ใบพัดหมุนติ้ว',
  ],
  ['하늘을 나는 새', 'A Bird in the Sky', 'Chim bay trên trời', '飞在天空的鸟', 'นกที่บินบนฟ้า'],
  [
    '다 같이 타는 버스',
    'A Bus for Everyone',
    'Cùng lên xe buýt',
    '大家一起坐公交车',
    'รถบัสที่เราขึ้นด้วยกัน',
  ],
  ['땅속을 달려요', 'Racing Underground', 'Chạy dưới lòng đất', '在地下奔跑', 'วิ่งใต้ดิน'],
  [
    '우르릉 흙 나르기',
    'Rumbling Along with Soil',
    'Chở đất ầm ầm',
    '轰隆隆，运泥土',
    'ขนดินเสียงครืนครืน',
  ],
  [
    '도둑 잡는 순찰차',
    'The Patrol Car',
    'Xe tuần tra bắt trộm',
    '抓小偷的巡逻车',
    'รถสายตรวจจับขโมย',
  ],
  [
    '칙칙폭폭 빠른 기차',
    'The Speedy Choo-Choo Train',
    'Tàu hỏa chạy nhanh',
    '呜呜，飞快的火车',
    'รถไฟฉึกฉักแสนเร็ว',
  ],
  [
    '빙글빙글 콘크리트',
    'Mixing Concrete',
    'Trộn bê tông quay tròn',
    '转呀转，搅拌混凝土',
    'หมุนผสมคอนกรีต',
  ],
  [
    '아파도 걱정 마',
    'Don’t Worry When You’re Sick',
    'Đừng lo khi bị đau',
    '生病也别担心',
    'ป่วยก็ไม่ต้องกังวล',
  ],
  [
    '힘센 땅 파는 친구',
    'Our Strong Digging Friend',
    'Người bạn đào đất khỏe mạnh',
    '力气大的挖土朋友',
    'เพื่อนขุดดินจอมพลัง',
  ],
  [
    '삐뽀삐뽀 불자동차',
    'The Fire Engine',
    'Xe cứu hỏa hú còi',
    '呜呜呜，消防车',
    'รถดับเพลิงปี้ป้อ',
  ],
  ['내일 또 만나요', 'See You Tomorrow', 'Hẹn gặp lại ngày mai', '明天再见', 'พรุ่งนี้เจอกันใหม่'],
  ['이거 무슨 냄새?', 'What’s That Smell?', 'Mùi gì thế nhỉ?', '这是什么味道？', 'กลิ่นอะไรนะ'],
  ['나도 미안해', 'I’m Sorry Too', 'Tớ cũng xin lỗi', '我也很抱歉', 'ฉันก็ขอโทษเหมือนกัน'],
  [
    '안 돼, 위험해!',
    'Stop, It’s Dangerous!',
    'Đừng, nguy hiểm đấy!',
    '不行，危险！',
    'อย่านะ อันตราย!',
  ],
  [
    '나만 미워하는 것 같아',
    'Does Nobody Like Me?',
    'Hình như mọi người ghét tớ',
    '好像大家都讨厌我',
    'เหมือนทุกคนไม่ชอบฉันเลย',
  ],
  ['범인은 누구?', 'Who Did It?', 'Ai là thủ phạm?', '是谁干的？', 'ใครเป็นคนทำ'],
  [
    '짝꿍은 누구랑?',
    'Who Will Be My Partner?',
    'Ai sẽ là bạn cùng nhóm?',
    '谁和我做搭档？',
    'ใครจะเป็นคู่ของฉัน',
  ],
  [
    '너랑 안 놀아!',
    'I Won’t Play with You!',
    'Tớ không chơi với cậu!',
    '我不跟你玩！',
    'ฉันไม่เล่นกับเธอแล้ว!',
  ],
  [
    '걱정 몽글이, 안녕!',
    'Goodbye, Little Worry!',
    'Tạm biệt, nỗi lo nhỏ!',
    '再见，小烦恼！',
    'ลาก่อน เจ้าความกังวล',
  ],
  ['내가 그랬어', 'It Was Me', 'Chính tớ đã làm', '是我做的', 'ฉันเป็นคนทำเอง'],
  [
    '옛날 옛적 깜빡 도깨비',
    'The Forgetful Goblin',
    'Ngày xưa có yêu tinh hay quên',
    '从前有个健忘的鬼怪',
    'กาลครั้งหนึ่งมีโทแกบีขี้ลืม',
  ],
  ['밥 먹기 대장', 'The Mealtime Champion', 'Nhà vô địch ăn cơm', '吃饭小能手', 'แชมป์กินข้าว'],
  [
    '으앙, 실수했어',
    'Oops, I Made a Mistake',
    'Ôi, tớ mắc lỗi rồi',
    '哎呀，我犯错了',
    'แง ฉันทำพลาดแล้ว',
  ],
  ['아차, 깜빡했다', 'Oops, I Forgot', 'Ôi, tớ quên mất', '哎呀，忘记了', 'อุ๊ย ลืมไปเลย'],
  [
    '무지개반의 하루',
    'A Day in Rainbow Class',
    'Một ngày ở lớp Cầu Vồng',
    '彩虹班的一天',
    'หนึ่งวันในห้องสายรุ้ง',
  ],
  [
    '선생님이 좋아졌어',
    'I Like My Teacher Now',
    'Tớ thích cô giáo rồi',
    '我开始喜欢老师了',
    'ฉันชอบคุณครูแล้ว',
  ],
  [
    '배 아파, 집에 가고 싶어',
    'My Tummy Hurts, I Want to Go Home',
    'Đau bụng quá, tớ muốn về nhà',
    '肚子疼，我想回家',
    'ปวดท้องจัง อยากกลับบ้าน',
  ],
  ['안녕, 이 한마디', 'One Little Hello', 'Một lời chào nhỏ', '一句你好', 'คำทักทายเล็ก ๆ'],
  [
    '나도 무지개반 갈래',
    'I Want to Join Rainbow Class Too',
    'Tớ cũng muốn vào lớp Cầu Vồng',
    '我也想去彩虹班',
    'ฉันก็อยากไปห้องสายรุ้ง',
  ],
  [
    '다들 어디 가?',
    'Where Is Everyone Going?',
    'Mọi người đi đâu thế?',
    '大家去哪儿？',
    'ทุกคนไปไหนกัน',
  ],
];
const titles = new Map(rows.map(([ko, en, vi, zh, th]) => [ko, { en, vi, zh, th }]));
export function legacyLibraryTitle(title: string, lang: string): string | undefined {
  const match = title.match(/^(\d+\.\s*)(.*)$/);
  const key = match ? match[2] : title;
  const translated = titles.get(key)?.[lang as 'en' | 'vi' | 'zh' | 'th'];
  return translated ? `${match?.[1] ?? ''}${translated}` : undefined;
}
